### ISSUE TITLE
移动4G  cmnet 连不上

### ISSUE THREAD

**Issue by jmireles7** [shadowsocks/shadowsocks-android#2143] opened 2019-03-03 03:19 UTC
Please read contributing guidelines. Thanks.

**Describe the bug**

移动4G连上有问题，dns请求发不出去的样子，表现为连上后网页打不开，而telegram却能正常使用，同样的节点配置，使用v2rayNG 的ss功能可以正常连接！

根据之前的issues
https://github.com/shadowsocks/shadowsocks-android/issues/591

改DNS检查为allowed，无效
APN连接点的端口为80，无效
APN协议从"ipv4/ipv6"改成"ipv4"，无效

补充，发现APN改为cmwap可以连上，改回cmnet又不行！cmwap无法使用微信的语音视频等功能…蛋疼

使用v2rayNG 的ss功能两个APN都能正常连接！
望大佬看看原因…

**To Reproduce**

1. 关闭wifi
2. 启动 shadowsocks 并连接
3. 开启google
4. 查看错误

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android  8.0   OxygenOS 5.0.8
 - Device: [ OnePlus 3T ]
 - Version: [ONEPLUS A3010_28_181206]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8 (修改过，并无改善)
*[x]  DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

上截图，为防止是线路导致的问题，我在家里的树莓派安装服务端，
![404](https://user-images.githubusercontent.com/34878932/53811256-e4084380-3f93-11e9-9834-07aa643c3062.jpg)
![_20190305221241](https://user-images.githubusercontent.com/34878932/53811259-e4084380-3f93-11e9-8c63-aaab1a094095.jpg)
![_20190305221245](https://user-images.githubusercontent.com/34878932/53811260-e4a0da00-3f93-11e9-85b8-edbec49ba82b.jpg)
![_20190305221249](https://user-images.githubusercontent.com/34878932/53811261-e4a0da00-3f93-11e9-9286-6e4863f34349.jpg)

连接后访问国内网站某度，完全无法打开，截图中可以看到，shadowsocks 中间有发送与接收数据，由于找不到可以直接用ip访问的网站，我访问 http://119.29.29.29/，虽然是个404页面，但确实打开了。  然后某些直接使用ip连接的app也没有问题。

V2客户端正常

![_20190305221434](https://user-images.githubusercontent.com/34878932/53811337-203ba400-3f94-11e9-95b0-4ed3c16ddf44.jpg)
![_20190305221437](https://user-images.githubusercontent.com/34878932/53811338-20d43a80-3f94-11e9-8e10-7b9ba204769b.jpg)

最后， 把APN换成  CMWAP 后就能正常打开网页  - - 

@madeye

**Comment by Mygod** [comment] 2019-03-06 17:55
Disable DNS over UDP.

**Comment by jmireles7** [comment] 2019-03-08 07:15
@Mygod   恕在下愚钝，只找到DNS Forwading，并没有找到DNS over UDP 这个选项，而DNS Forwading开关并无改善此问题。

**Comment by Mygod** [comment] 2019-03-08 07:17
Use latest beta release.

**Comment by everthis** [comment] 2019-03-12 07:42
same here, using  v7.4.2

**Comment by userid** [comment] 2019-03-14 13:37
这是因为北京移动会偶尔禁掉正常的udp流量。而ss好像总会走一部分的UDP。

**Comment by jmireles7** [comment] 2019-03-15 01:16
@Mygod  使用 GooglePlay 最新Beta版 4.7.3测试，问题依然存在。

**Comment by everthis** [comment] 2019-03-15 03:08
Version 4.6.1 has the same problem on Galaxy s10 over China mobile network.

**Comment by Mygod** [comment] 2019-03-15 09:28
Sounds like it might be local DNS issue. Dump logcat?

**Comment by jmireles7** [comment] 2019-03-16 02:13
[log.txt](https://github.com/shadowsocks/shadowsocks-android/files/2973371/log.txt)
我点击了若干次测试连接，并保存了 logcat 输出，请查看附件txt   @Mygod

**Comment by luvvien** [comment] 2019-03-19 04:27
[Outline](https://vien.tech/article/93) 了解一下

**Comment by madeye** [comment] 2019-03-19 08:57
@Mygod Is it possible an IPv6 related issue, as CMNET may assign IPv6 address to the client.

**Comment by madeye** [comment] 2019-03-19 09:20
@jmireles7 Could you check that if you enabled IPv6 route? If yes, please try disable it.

**Comment by Mygod** [comment] 2019-03-19 09:46
@madeye Just tested with cmnet with IPv6, everything seems fine.

**Comment by everthis** [comment] 2019-03-20 13:21
Hello, I'm having trouble on my phone over China Mobile network in Beijing. I shared the same config through QR code with one of my colleagues(whose ISP is China Unicom). And everything was fine on his phone. 

Besides, if I use China Unicom network with the same phone and the same SS config, everything is fine.

Here are some screenshots on my phone. Is there anything I can do to debug?

![20190320_204950](https://user-images.githubusercontent.com/3142886/54686126-8a874380-4b53-11e9-822f-e4f85f2febdd.jpg)
![Screenshot_20190320-210355_Shadowsocks](https://user-images.githubusercontent.com/3142886/54686474-582a1600-4b54-11e9-8772-bd6b55d26f4c.jpg)

**Comment by jmireles7** [comment] 2019-03-21 15:33
Hi,
CMNET确实为我分配了一个IPV6的地址，但是在APP中关闭IPV6路由后依然面临同样的问题。

**Comment by yzou** [comment] 2019-03-27 15:31
这个问题应该是修改了tun2socks 里面的dns gw 导致的，移动网络会分配一个dns 地址，dns 请求会发送到这个地址，然后只有发到172.19.0.2 地址的dns 请求才会tunnel 到配置的8.8.8.8，发到移动的dns 地址的dns请求会做 udprelay，但可能境外服务器请求不到移动的dns

badvpn commit：
https://github.com/shadowsocks/badvpn/commit/ba4c45d6b4d30fd6b2557e92a770ccae12ec9257

网卡dns 配置：
rmnet0:
221.179.155.193
221.179.155.209
2049:8000:2000:0:70::1
2049:8000:2000:0:170::1

tun0:
172.19.0.2

log 如下：

> 2019-03-27 22:46:47.948 23511-23511/? D/shadowsocks: [udp] server receive a packet
2019-03-27 22:46:47.948 23511-23511/? D/shadowsocks: [1080] [udp] cache hit: 221.179.155.209:53 <-> 127.0.0.1:35443
2019-03-27 22:46:50.952 23511-23511/? D/shadowsocks: [udp] server receive a packet
2019-03-27 22:46:50.952 23511-23511/? D/shadowsocks: [1080] [udp] cache hit: 221.179.155.193:53 <-> 127.0.0.1:60414
2019-03-27 22:46:52.955 23511-23511/? D/shadowsocks: [udp] server receive a packet
2019-03-27 22:46:52.956 23511-23511/? D/shadowsocks: [1080] [udp] cache hit: 221.179.155.193:53 <-> 127.0.0.1:35443
2019-03-27 22:46:55.963 23511-23511/? D/shadowsocks: [udp] server receive a packet
2019-03-27 22:46:55.963 23511-23511/? D/shadowsocks: [1080] [udp] cache miss: 221.179.155.193:53 <-> 127.0.0.1:56281
2019-03-27 22:46:57.965 23511-23511/? D/shadowsocks: [udp] server receive a packet
2019-03-27 22:46:57.965 23511-23511/? D/shadowsocks: [1080] [udp] cache miss: 221.179.155.193:53 <-> 127.0.0.1:38138

**Comment by yzou** [comment] 2019-03-27 16:15
把这个改动回退就可以用移动网络了

shadowsocks/badvpn@ba4c45d

**Comment by Mygod** [comment] 2019-03-27 16:54
@yzou Interesting. I don't think reverting that commit is the right fix. Can you fill out the issue template as well? I will take a look later.

**Comment by madeye** [comment] 2019-03-27 22:40
It's possible that some app won't follow system's default DNS settings.

I think it's safe to revert that change, given there's no complain about that for years.

**Comment by Mygod** [comment] 2019-03-28 05:07
@madeye I don't think this is an app specific issue. For some reason, it seems to be sending its DNS queries to the wrong interface (a ROM-specific bug?). Our current implementation calls `Network.getAllByName` API to do local DNS resolving but maybe we need to check whether this API is working properly on older APIs. (as far as I remember, it's working perfectly on Android 9)

**Comment by madeye** [comment] 2019-03-28 07:09
IIRC, browsers like Chrome / FIrefox will use its own DNS resolver. Then we may see this kind of problems:

1. An app reads the DNS config from system and connect to them directly.
2. VPN connection is setup.
3. That app keeps sending DNS queries to previous system's DNS, but cannot be redirected by tun2socks.
4. DNS leak happens.

**Comment by yzou** [comment] 2019-03-28 07:18
> @yzou Interesting. I don't think reverting that commit is the right fix. Can you fill out the issue template as well? I will take a look later.

@Mygod You can reproduce by connecting ss under wifi network, and then disable wifi network, then for China Mobile cmnet, rmnet0 interface will be active and set China Mobile DNS server on this interface.

I'm in Beijing using Huawei P20 Pro, my rmnet0 DNS servers are active after switching from wifi to mobile data.

I use this app to check interfaces' DNS config:
https://play.google.com/store/apps/details?id=com.frostnerd.dnschanger&rdid=com.frostnerd.dnschanger

**Comment by Mygod** [comment] 2019-03-28 08:00
Please fill out the issue template.

**Comment by yzou** [comment] 2019-03-28 12:34
@Mygod see #2180

**Comment by Mygod** [comment] 2019-03-29 03:26
> IIRC, browsers like Chrome / FIrefox use their own DNS resolvers. Then we may see this kind of problem:
> 
> 1. An app reads the DNS config from system and connect to them directly.
> 2. VPN connection is setup.
> 3. That app keeps sending DNS queries to previous system's DNS, but cannot be redirected by tun2socks.
> 4. DNS leak (to the remote server) happens.

Tested on com.android.chrome 73.0.3683.90. Failed to observe such behavior. In fact everything works as expected. Additionally, I do not think this app should be responsible for other app/ROM's bugs.

**Comment by Mygod** [comment] 2019-03-29 09:15
_Originally posted by @madeye in https://github.com/shadowsocks/shadowsocks-android/issues/2180#issuecomment-477895914_
> I cannot reproduce this problem with EMUI 9.0 on China Union network.
> 
> Since only CMNET has this issue, I guess it maybe related to VoIP.
> 
> So please help to confirm if VoIP enabled. If enabled, please disable it and try again.

I do have both VoLTE and Wi-Fi calling enabled on my CMNET card. Still cannot reproduce.

**Comment by yzou** [comment] 2019-03-29 10:48
Connect ss under China Mobile 4G network, and sleep phone for a while, e.g. half an hour, I can see dns to China Mobile's DNS server in log:

![image](https://user-images.githubusercontent.com/1464693/55227540-b80a7600-5252-11e9-9685-d4888127c89b.png)

And this time, I can't open any sites, including Twitter app.

The chrome error msg is:

> You connection was interrupted
A netwrok change was detected
ERR_NETWORK_CHANGED

**Comment by Mygod** [comment] 2019-03-29 10:55
You mentioned put your phone to idle so I think your issue is unrelated to #2143.

**Comment by yzou** [comment] 2019-03-29 10:58
> Connect ss under China Mobile 4G network, and sleep phone for a while, e.g. half an hour, I can see dns to China Mobile's DNS server in log:
> 
> ![image](https://user-images.githubusercontent.com/1464693/55227540-b80a7600-5252-11e9-9685-d4888127c89b.png)
> 
> And this time, I can't open any sites, including Twitter app.
> 
> The chrome error msg is:
> 
> > You connection was interrupted
> > A netwrok change was detected
> > ERR_NETWORK_CHANGED

Back from sleep, I saw these log, it must be the reason of network broken （only qq can receive msg）:

> 2019-03-29 18:50:17.654 1223-14623/? V/ActivityManager: Activity slept: token=Token{8d29eec ActivityRecord{ffefd9f u0 com.github.shadowsocks/.MainActivity t13669}} callingPid=0
2019-03-29 18:50:35.178 1223-1300/? I/NotificationService: enqueueNotificationInternal: pkg=com.github.shadowsocks id=1 notification=Notification(channel=service-vpn pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0xff607d8b vis=PRIVATE)
2019-03-29 18:50:35.180 1223-1300/? I/NotificationService: enqueueNotificationInternal Channel Info : pkg=com.github.shadowsocks id=1 importance =2
2019-03-29 18:50:35.229 2882-3003/? I/AppManager: app:com.github.shadowsocks Notification update time:920126195
2019-03-29 18:50:58.121 27216-18428/? I/chatty: uid=10197(com.github.shadowsocks) DefaultDispatch identical 1 line
2019-03-29 18:51:15.874 1223-5092/? V/ActivityManager: Activity slept: token=Token{8d29eec ActivityRecord{ffefd9f u0 com.github.shadowsocks/.MainActivity t13669}} callingPid=0
2019-03-29 18:51:18.440 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:18.442 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 23 lines
2019-03-29 18:51:18.442 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:20.489 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:20.492 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:22.538 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:22.541 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:24.585 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:24.587 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:24.588 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:25.444 1223-1300/? I/NotificationService: enqueueNotificationInternal: pkg=com.github.shadowsocks id=1 notification=Notification(channel=service-vpn pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0xff607d8b vis=PRIVATE)
2019-03-29 18:51:25.446 1223-1300/? I/NotificationService: enqueueNotificationInternal Channel Info : pkg=com.github.shadowsocks id=1 importance =2
2019-03-29 18:51:25.497 2882-3003/? I/AppManager: app:com.github.shadowsocks Notification update time:920176463
2019-03-29 18:51:25.500 11639-11639/? D/NotificationEntryMgr: updateNotification(StatusBarNotification(pkg=com.github.shadowsocks user=UserHandle{0} id=1 tag=null key=0|com.github.shadowsocks|1|null|10197: Notification(channel=service-vpn pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x62 color=0xff607d8b vis=PRIVATE)))
2019-03-29 18:51:25.509 11639-11667/? D/ReporterUtil:  e id:344 type:{pkg:com.github.shadowsocks,hw_type:null,hw_btw:false,onGoing:true,importance:2}
2019-03-29 18:51:26.633 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:26.635 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:28.681 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:28.682 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 7 lines
2019-03-29 18:51:28.683 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:30.728 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:30.733 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:32.777 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:32.778 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 5 lines
2019-03-29 18:51:32.778 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:34.825 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:34.825 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 1 line
2019-03-29 18:51:34.825 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:36.872 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:36.874 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 7 lines
2019-03-29 18:51:36.874 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:38.921 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:38.922 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 3 lines
2019-03-29 18:51:38.924 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:40.969 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:40.974 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 16 lines
2019-03-29 18:51:40.974 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:43.016 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:43.018 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 8 lines
2019-03-29 18:51:43.018 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:45.065 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:45.067 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 10 lines
2019-03-29 18:51:45.068 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:46.341 27216-27648/? I/chatty: uid=10197(com.github.shadowsocks) DefaultDispatch identical 1 line
2019-03-29 18:51:47.113 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:47.114 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 4 lines
2019-03-29 18:51:47.114 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:49.161 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:49.162 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 1 line
2019-03-29 18:51:49.162 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:51.209 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:51.214 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 7 lines
2019-03-29 18:51:51.214 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:53.257 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:53.261 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 16 lines
2019-03-29 18:51:53.262 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:54.720 1223-14623/? V/ActivityManager: Activity slept: token=Token{8d29eec ActivityRecord{ffefd9f u0 com.github.shadowsocks/.MainActivity t13669}} callingPid=0
2019-03-29 18:51:55.305 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:55.310 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 20 lines
2019-03-29 18:51:55.310 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:57.353 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:57.355 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 8 lines
2019-03-29 18:51:57.356 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:59.401 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:51:59.407 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 28 lines
2019-03-29 18:51:59.408 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:01.448 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:01.450 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 7 lines
2019-03-29 18:52:01.450 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:01.451 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:01.451 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:01.451 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:01.452 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 3 lines
2019-03-29 18:52:01.452 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:03.226 26639-21619/? V/FA-SVC: Fetching remote configuration: com.github.shadowsocks
2019-03-29 18:52:03.496 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:05.545 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:05.551 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 16 lines
2019-03-29 18:52:05.551 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:07.593 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:07.607 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 22 lines
2019-03-29 18:52:07.607 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:09.641 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:09.651 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 12 lines
2019-03-29 18:52:09.652 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:11.689 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:11.697 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 15 lines
2019-03-29 18:52:11.698 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:13.737 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected
2019-03-29 18:52:13.747 12043-12043/? I/chatty: uid=10197(com.github.shadowsocks) /data/app/com.github.shadowsocks-HmiSya_RBDoipJt3enF-bw==/lib/arm64/libss-local.so identical 19 lines
2019-03-29 18:52:13.747 12043-12043/? E/shadowsocks: getpeername: Transport endpoint is not connected

**Comment by yzou** [comment] 2019-03-29 11:01
> You mentioned put your phone to idle so I think your issue is unrelated to #2143.

It's not a must.

**Comment by madeye** [comment] 2019-03-29 11:52
```
getpeername: Transport endpoint is not connected
```
Means shadowsocks client cannot reach the server. It looks our background service is killed or suspended by the system.

Make sure you exclude shadowsocks from battery optimization in EMUI.

**Comment by yzou** [comment] 2019-03-29 12:35
I can see all processes active in bg through ps -Af

**Comment by zxkane** [comment] 2019-04-11 11:38
遇到类似的问题，在联通4g网络下部分app(Google doc)不能走VPN连接。同样的服务端，同样的配置。4g下可以在浏览器或 app google访问google。ss测试连接服务端也正常。

Wifi下就没有问题，各种服务都可以访问。

一加5，andriod9

**Comment by Aodi** [comment] 2019-04-19 08:19
北京移动，ssr，4G不行，wifi正常。试了多种解决方法，都不能解决。

**Comment by madeye** [comment] 2019-04-19 08:27
@yzou please help to confirm the issue is fixed in latest version.

**Closed** 2019-04-22 01:28 UTC
Labels: cannot reproduce

**Comment by yzou** [comment] 2019-04-22 10:32
> @yzou please help to confirm the issue is fixed in latest version.

It's fixed. Great work!

**Comment by redone2000** [comment] 2019-05-20 06:26
我大概是最近几周发现了这个问题，就是用中国移动的4G网络，无法ss，不管是在iPhone上还是共享给mac时，都无法使用，后来无意中在iPhone上下载到一个yoururl vpn，居然完美使用，哈哈哈

**Comment by wxysystem32** [comment] 2019-05-24 06:25
> 
> 
> > @yzou please help to confirm the issue is fixed in latest version.
> 
> It's fixed. Great work!

Hi,how to fix the issue?

**Comment by wsz7777** [comment] 2019-05-27 15:24
阿里云搭建nginx转发至国外vps

**Comment by xiangrikui88200** [comment] 2019-06-02 18:47
[https://github.com/shadowsocks/shadowsocks-android/issues/344](url)
这里面的答案经实测有效

**Comment by fayeyuan** [comment] 2019-10-05 05:53
https://github.com/shadowsocks/shadowsocks-android/issues/591
苹果手机有解决方案吗？

先切换一下代理模式，然后开关几次飞行模式，然后切回原来的代理模式。亲测有效。

**Comment by wangfeng35** [comment] 2019-11-18 06:44
> ，ssr，4G不行，wifi正常。试了多种解决方法，都不能解决。

最近开始频繁出现这个问题 联通 无线网络都没有问题 就移动4G完全不行了

**Comment by AlexMao9527** [comment] 2019-11-24 11:17
我原本也是wifi能上流量不能上，持续了1个月多时间，刚才在你的贴子下面找到了一个解决方法：就是把IPv6给关了，我就能上了。原本是扫码导入的，它自动打开了IPv6。(流量卡为中国移动)

**Comment by fansmc** [comment] 2019-11-25 06:38
刚试了，关掉IPV6 就好了； 之前是一样的问题， WIFI下正常， 移动4G网络各种找不到网站

**Comment by yzou** [comment] 2019-11-25 06:44
> 刚试了，关掉IPV6 就好了； 之前是一样的问题， WIFI下正常， 移动4G网络各种找不到网站

在哪里关 IPV6，手机系统的网络设置里面吗？

**Comment by wangfeng35** [comment] 2019-11-25 06:47
> 刚试了，关掉IPV6 就好了； 之前是一样的问题， WIFI下正常， 移动4G网络各种找不到网站

我关了还是不行。。。真是无语了

**Comment by stevenlee87** [comment] 2019-11-26 04:01
北京移动4G ，使用ss4.8.5 不行。使用WIFI正常。
尝试关掉ss的IPV6还是不行。

**Comment by wangfeng35** [comment] 2019-11-26 04:02
> 北京移动4G ，使用ss4.8.5 不行。使用WIFI正常。
> 尝试关掉ss的IPV6还是不行。

是的 我北京移动4G这样依然不行 但是换成ssr竟然就能用了 搞不懂

**Comment by fansmc** [comment] 2019-11-26 08:02
> > 刚试了，关掉IPV6 就好了； 之前是一样的问题， WIFI下正常， 移动4G网络各种找不到网站
> 
> 在哪里关 IPV6，手机系统的网络设置里面吗？

惨了， 今天又没用了》。。  就在app里面 配置里有个IPV6转发的开关
昨天本来也是不行， 关掉这个开关就行了
但是今天不止为何 怎么弄都不行了...

**Comment by wangfeng35** [comment] 2019-11-26 08:03
> > > 刚试了，关掉IPV6 就好了； 之前是一样的问题， WIFI下正常， 移动4G网络各种找不到网站
> > 
> > 
> > 在哪里关 IPV6，手机系统的网络设置里面吗？
> 
> 惨了， 今天又没用了》。。 就在app里面 配置里有个IPV6转发的开关
> 昨天本来也是不行， 关掉这个开关就行了
> 但是今天不止为何 怎么弄都不行了...

移动4G墙中墙

**Comment by madeye** [comment] 2019-11-27 01:12
For anyone has problems with CMNET, please try to change the routing option to `All` and report back. Thanks!

**Comment by wyLeon** [comment] 2019-11-27 17:09
同样的问题..困扰已久

**Comment by snowicepeng** [comment] 2019-11-28 02:41
> 北京移动，ssr，4G不行，wifi正常。试了多种解决方法，都不能解决。

In APN setting, remove the IPV6 and restart network.

**Comment by chenbojian** [comment] 2019-12-06 10:04
Still not work in new release for mobile 4G. Showing Read error: ssl=0x70eb843588

**Comment by madeye** [comment] 2019-12-06 10:31
@chenbojian Try this plugin: https://github.com/shadowsocks/v2ray-plugin

**Comment by chenbojian** [comment] 2019-12-06 11:13
@madeye I tried the very basic setting with v2ray-plugin. And tried several times between using and not using plugin.

- With v2ray-plugin it works and it is very stable.
- Without v2ray-plguin it can not work.

**Comment by madeye** [comment] 2019-12-06 11:17
Okay, I think we finally knows what CMNET is doing. They deploys a white list of network protocols on their network. The best solution is avoiding their service.

So it's a not an issue of shadowsocks.

**Comment by chenbojian** [comment] 2019-12-06 11:40
I think avoid their service is not a good choice. Most people are using china mobile.
Can you help  to explain more to me about the white list of protocols.
From my understanding, cmnet is able to connect to my server. My ss-server is producing some valid logs. I guess TCP works fine. Do you mean the UDP is blocked?

**Comment by madeye** [comment] 2019-12-06 11:56
If so, keep using v2ray-plugin, it helps obfuscate shadowsocks traffic to normal TLS traffic.

**Comment by Mygod** [comment] 2019-12-06 12:52
Interesting. Can people report whether this still occurs if they use test
connection under proxy-only mode?

**Comment by wyLeon** [comment] 2019-12-06 14:00
移动4G无法连接SSR解决方案汇总--以SAMSUNG S7edge为例 - VinceW的文章 - 知乎
https://zhuanlan.zhihu.com/p/94088821

**Comment by wyLeon** [comment] 2019-12-06 14:02
Wrote an article to solve the problem. 
移动4G无法连接SSR解决方案汇总--以SAMSUNG S7edge为例 - VinceW的文章 - 知乎
https://zhuanlan.zhihu.com/p/94088821

**Comment by AlexMao9527** [comment] 2019-12-06 14:27
我添加不成功啊，上面说我没有添加dun类型的APN权限。

**Comment by everthis** [comment] 2020-03-11 16:10
USE v2ray-plugin to solve this issue!
