### ISSUE TITLE
Per-app VPN has no effect (v3.2.4)

### ISSUE THREAD

**Issue by tobyxdd** [shadowsocks/shadowsocks-android#936] opened 2016-10-12 11:04 UTC
### Environment

* Android version: Cyanogenmod 13 (Android 6.0.1)
* Device: Huawei Nexus 6P
* Shadowsocks version: v3.2.4

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Local port: 1080
* Encrypt method: AES-128
* [ ] One-time authentication
* Route:
* [ ] IPv6 route
* [x] Per-App Proxy
  * [x] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

Turned on per-app proxy

### What did you expect to see?

Only the specified apps should be tunneled over Shadowsocks. (or not tunneled if it's bypass mode)

### What did you see instead?

All apps are tunneled over Shadowsocks. This feature is working in v3.1.4 (Didn't try any other version between) so I guess the problem was recently introduced 😢

**Comment by madeye** [comment] 2016-10-12 11:06
Why you say all apps are proxies?

**Comment by tobyxdd** [comment] 2016-10-12 11:12
我直接说中文吧...我之前一直用的是分应用代理（绕行模式），把国产应用都选出来绕行，其他的走shadowsocks 之前一直很正常 但是今天更新了v3.2.4发现分应用代理失效了 所有程序都走shadowsocks了 我试着降级到3.2.3问题依旧 直接降级到3.1.4就恢复正常了 确认不是配置问题 所以我感觉bug应该是3.1.4-3.2.3这期间引入的。。

**Comment by madeye** [comment] 2016-10-12 11:30
Again, how to reproduce your problem?  Specifically, in which steps you verified that all of your apps are proxied?

**Comment by tobyxdd** [comment] 2016-10-12 11:33
一开始发现是因为我用csploit不正常了 结果用浏览器测试了 把几个浏览器分别都加入到绕行列表结果依然走的是shadowsocks

**Comment by madeye** [comment] 2016-10-12 11:43
1. If you're using Chrome, make sure the "Data Saver" is not enabled. Similar issue: https://github.com/shadowsocks/shadowsocks-android/issues/934
2. I cannot reproduce your issue locally, Actually, per-app proxy function doesn't change for months.

**Comment by tobyxdd** [comment] 2016-10-13 00:01
Just tried 3.2.5, the problem no longer exists...

Max Lv <notifications@github.com>于2016年10月12日周三 19:44写道：

**Comment by Mygod** [comment] 2016-10-13 04:11
Hmm suppose we can close it for now.

**Closed by Mygod** 2016-10-13 04:11 UTC
Labels: cannot reproduce
