### ISSUE TITLE
无法解析在cloudflare上创建的域名

### ISSUE THREAD

**Issue by tian-le** [shadowsocks/shadowsocks-android#2760] opened 2021-07-07 13:59 UTC
发现shadowsocks-android无法解析指向cloudflare的nameserver的域名
如果不用域名而直接使用IP地址->没有问题
局域网内其它设备能够解析域名 手机其它的app也能成功解析域名
用outline也没问题
使用的并不是二级动态域名 而是自己的一级域名 域名的IP地址记录是在cloudflare上定义的 然后域名指向cloudflare的nameserver
先前域名用的其它的nameserver 也没有问题
![image](https://user-images.githubusercontent.com/13028261/124770522-be354400-df7d-11eb-9253-89253a7bab92.png)
偶尔能看到这个错误信息 无法解析cp.cloudflare.com
![image](https://user-images.githubusercontent.com/13028261/124772370-5122ae00-df7f-11eb-83e1-ececb851d20f.png)
麻烦看看这个问题?

**Comment by mengxinziqiang** [comment] 2021-07-08 07:58
我也有同样的报错，这两天才出现的，之前是正常的

**Comment by tian-le** [comment] 2021-07-08 08:08
我今天又多试了一阵子 发现似乎并不是cloudflare的问题 用namecheap做nameserver问题也是一样的 我试过5.2.4和5.2.5都有这个问题 恐怕是dns解析那块有问题

**Comment by mengxinziqiang** [comment] 2021-07-08 08:16
我一直是使用的5.1.4版本，大概半年了，一直没出现意外，我正在排查服务器的问题。

**Comment by andrei15** [comment] 2021-07-08 15:33
I have this or same error if I use Settings → Network & internet → Advanced → Private DNS.
If off private DNS all work done.

**Comment by tian-le** [comment] 2021-07-09 00:35
I cannot find this option frok my side for unknown reason.
![Screenshot_2021-07-09-10-33-21](https://user-images.githubusercontent.com/13028261/125006331-38aab480-e0a1-11eb-96ad-7878fb56adf2.png)

> I have this or same error if I use Settings → Network & internet → Advanced → Private DNS.
> If off private DNS all work done.

**Comment by Mygod** [comment] 2021-07-09 02:42
> I have this or same error if I use Settings → Network & internet → Advanced → Private DNS.
> If off private DNS all work done.

Could not reproduce on Android 12 beta.

**Comment by andrei15** [comment] 2021-07-09 04:34
> I cannot find this option frok my side for unknown reason.
> ![Screenshot_2021-07-09-10-33-21](https://user-images.githubusercontent.com/13028261/125006331-38aab480-e0a1-11eb-96ad-7878fb56adf2.png)
> 
> > I have this or same error if I use Settings → Network & internet → Advanced → Private DNS.
> > If off private DNS all work done.

This settings (Settings → Network & internet → Advanced → Private DNS)  is the global Android system settings not in shadowsocks application.

**Comment by Abdipour** [comment] 2021-07-15 07:33
Duplicate of #2606

**Comment by Abdipour** [comment] 2021-07-15 14:36
I have the same problem only in android TV. I use shadowsocks-rust + v2ray-plugin.
Android and windows clients works fine. I tried to import json config from both clients in android tv.
Also I tried to connect another VPN service to test my internet. After VPN connection established, shadowsocks client successfully connected.
Screenshot of test reachability to cp.cloudflare.com:
![image](https://user-images.githubusercontent.com/23517827/125644348-7c6596db-6efb-4c5f-bf61-94bce69370d6.png)

**Comment by Abdipour** [comment] 2021-07-15 14:37
> > I cannot find this option frok my side for unknown reason.
> > ![Screenshot_2021-07-09-10-33-21](https://user-images.githubusercontent.com/13028261/125006331-38aab480-e0a1-11eb-96ad-7878fb56adf2.png)
> > > I have this or same error if I use Settings → Network & internet → Advanced → Private DNS.
> > > If off private DNS all work done.
> 
> This settings (Settings → Network & internet → Advanced → Private DNS) is the global Android system settings not in shadowsocks application.

Unfortunately android TV does not have this settings.

**Comment by Mygod** [comment] 2021-08-06 22:54
Closing due to inactivity.

**Closed by Mygod** 2021-08-06 22:54 UTC
Labels: cannot reproduce
