### ISSUE TITLE
tun2socks: udp out of buffer errors

### ISSUE THREAD

**Issue by yzou** [shadowsocks/shadowsocks-android#2414] opened 2020-01-21 08:39 UTC
**Describe the bug**
Connected overnight,  the next day only TCP traffic is working, UDP/DNS will fail and can't open any sites.

**To Reproduce**
1. Global mode or Bypass China mode
2. UDP DNS is off
3. Connect a server
4. Leave it some time, or overnight
5. Can't open any site, but telegram, wechat, QQ and Facebook apps are working

**Expected behavior**
Should work for all apps

**Screenshots**
Not applicable

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: 10.0.0.143
 - Device: Huawei P20 Pro
 - Version: EMUI 10,  C00E143R1P4patch01
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [x] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
From adb logcat:
```
2020-01-21 16:08:43.860 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:43.860 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:43.982 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:45.600 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:45.866 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:45.988 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:47.606 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:47.869 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:47.992 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:49.609 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:49.873 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:49.993 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:51.612 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:51.876 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:51.996 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:53.617 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:53.881 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:53.999 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:55.620 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:55.884 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:56.002 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:57.623 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:57.887 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:58.005 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:59.625 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:08:59.889 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:00.009 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:01.629 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:02.014 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:03.636 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:04.017 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:05.642 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:06.020 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:07.645 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:08.022 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:09.647 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:10.026 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:11.649 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:12.029 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-21 16:09:13.653 31308-31308/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer

```

**Comment by madeye** [comment] 2020-01-21 09:44
I don't think it's related to tun2socks.

From your description, it looks that the local resolver got stuck. That explains why Telegram still works, which connects to IPs directly. @Mygod what do you think?

I cannot reproduce this issue with the same EMUI version. You may also try this https://club.huawei.com/thread-21446964-1-1.html

**Comment by Mygod** [comment] 2020-01-21 10:13
Well he said he disabled DNS over UDP so technically local resolver shouldn't get stuck...

**Comment by yzou** [comment] 2020-01-21 10:43
I have this issue on my Huawei phone for years, since 2017, Huawei Mate 9 Pro, I replace with P20 Pro in 2018, the issue still occurs almost several times a week. I saw the "out of UDP buffer" since 2017, I reported this before. But on Nexus 5, I didn't have this issue. I don't know whether it's related to Huawei's WLAN+ feature, seamless handover support between wifi and 4G.

I also found this document in VpnService.java about "seamless handover" feature:
https://developer.android.com/reference/kotlin/android/net/VpnService.Builder#establish()

> To avoid conflicts, there can be only one active VPN interface at the same time. Usually network parameters are never changed during the lifetime of a VPN connection. It is also common for an application to create a new file descriptor after closing the previous one. However, it is rare but not impossible to have two interfaces while performing a seamless handover. In this case, the old interface will be deactivated when the new one is created successfully. Both file descriptors are valid but now outgoing packets will be routed to the new interface. Therefore, after draining the old file descriptor, the application MUST close it and start using the new file descriptor. If the new interface cannot be created, the existing interface and its file descriptor remain untouched.

I think there may be some issues when "seamless handover" is active.

I often encounter the UDP issue when I leave the office and into an elevator without 4G signals. So I thought the underlying tun fd may have changed.

**Comment by yzou** [comment] 2020-01-21 11:34
> I don't think it's related to tun2socks.
> 
> From your description, it looks that the local resolver got stuck. That explains why Telegram still works, which connects to IPs directly. @Mygod what do you think?
> 
> I cannot reproduce this issue with the same EMUI version. You may also try this https://club.huawei.com/thread-21446964-1-1.html

The DNS works for now after changing this option to Auto, but I can still see "out of UDP buffer" in logs

**Comment by madeye** [comment] 2020-01-21 11:39
Just ignore the log there. it doesn't really matter.

**Comment by yzou** [comment] 2020-01-21 12:50
> Just ignore the log there. it doesn't really matter.

But why would the Auto Private DNS work on Emui 10?

**Comment by Mygod** [comment] 2020-01-21 13:50
I don't understand that log either. @madeye Why does it do that? 😛

**Comment by madeye** [comment] 2020-01-21 14:05
@Mygod I suspect the UDP socket is closed by third-party or something similar, causing the write() operation keeps failing.

Given DNS over UDP is already disabled, even UDP forwarding failed, DNS should still work correctly.

**Comment by yzou** [comment] 2020-01-21 15:06
> @Mygod I suspect the UDP socket is closed by third-party or something similar, causing the write() operation keeps failing.
> 
> Given DNS over UDP is already disabled, even UDP forwarding failed, DNS should still work correctly.

If UDP forwarding failed, the DNS packets can't go out through tun2sock to ss-local or ss-tunnel

**Comment by yzou** [comment] 2020-01-21 15:14
It's strange that when DNS can't forward, I found many UDP sessions direct to DNS server and DN sessions between tun and tun2socks.

After set private DNS to auto, I can see only UDP sessions like this:
> netstat -an -u
udp        0      0 0.0.0.0:54762           0.0.0.0:*
udp        0      0 0.0.0.0:38392           0.0.0.0:*
udp        0      0 0.0.0.0:46586           0.0.0.0:*
udp        0      0 0.0.0.0:46599           0.0.0.0:*
udp        0      0 0.0.0.0:34353           0.0.0.0:*
udp        0      0 0.0.0.0:34406           0.0.0.0:*

When DNS has issues, the UDP sessions looks like this:
> netstat -an -u
udp        0      0 0.0.0.0:51406           0.0.0.0:*
udp        0      0 172.19.0.1:2273         8.8.4.4:53              ESTABLISHED
udp        0      0 0.0.0.0:51432           0.0.0.0:*
udp        0      0 172.19.0.1:63721        8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:35316        8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:51720        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:51817        8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:64192        8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:47893        8.8.4.4:53              ESTABLISHED
udp        0      0 172.19.0.1:35608        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:15179        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:35671        8.8.4.4:53              ESTABLISHED
udp        0      0 172.19.0.1:27480        180.76.76.76:53         ESTABLISHED
udp        0      0 172.19.0.1:15213        8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:52085        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:52435        8.8.4.4:53              ESTABLISHED
udp        0      0 0.0.0.0:36059           0.0.0.0:*
udp        0      0 172.19.0.1:7422         8.8.4.4:53              ESTABLISHED
udp        0      0 172.19.0.1:3403         8.8.8.8:53              ESTABLISHED
udp        0      0 0.0.0.0:60753           0.0.0.0:*
udp        0      0 172.19.0.1:23894        8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:60773        180.76.76.76:53         ESTABLISHED
udp        0      0 0.0.0.0:44422           0.0.0.0:*
udp        0      0 172.19.0.1:7583         8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:56781        172.19.0.2:53           ESTABLISHED
udp        0      0 0.0.0.0:52687           0.0.0.0:*
udp        0      0 172.19.0.1:52692        180.76.76.76:53         ESTABLISHED
udp        0      0 172.19.0.1:24030        8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:3563         172.19.0.2:53           ESTABLISHED
udp        0      0 0.0.0.0:52722           0.0.0.0:*
udp        0      0 172.19.0.1:60927        8.8.4.4:53              ESTABLISHED
udp        0      0 0.0.0.0:56835           0.0.0.0:*
udp        0      0 172.19.0.1:52741        8.8.4.4:53              ESTABLISHED
udp        0      0 0.0.0.0:40467           0.0.0.0:*
udp        0      0 0.0.0.0:40483           0.0.0.0:*
udp        0      0 172.19.0.1:36395        8.8.8.8:53              ESTABLISHED
udp        0      0 0.0.0.0:44594           0.0.0.0:*
udp        0      0 0.0.0.0:53014           0.0.0.0:*
udp        0      0 172.19.0.1:20250        8.8.4.4:53              ESTABLISHED
udp        0      0 0.0.0.0:53049           0.0.0.0:*
udp        0      0 0.0.0.0:57146           0.0.0.0:*
udp        0      0 0.0.0.0:36674           0.0.0.0:*
udp        0      0 172.19.0.1:36719        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:8052         8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:40930        8.8.4.4:53              ESTABLISHED
udp        0      0 0.0.0.0:45034           0.0.0.0:*
udp        0      0 0.0.0.0:53249           0.0.0.0:*
udp        0      0 0.0.0.0:53251           0.0.0.0:*
udp        0      0 172.19.0.1:28677        172.19.0.2:53           ESTABLISHED
udp        0      0 0.0.0.0:53257           0.0.0.0:*
udp        0      0 0.0.0.0:40983           0.0.0.0:*
udp        0      0 0.0.0.0:57370           0.0.0.0:*
udp        0      0 172.19.0.1:24612        180.76.76.76:53         ESTABLISHED
udp        0      0 0.0.0.0:57384           0.0.0.0:*
udp        0      0 0.0.0.0:36919           0.0.0.0:*
udp        0      0 0.0.0.0:36920           0.0.0.0:*
udp     2688      0 192.168.3.75:68         192.168.1.1:67          ESTABLISHED
udp        0      0 172.19.0.1:41158        8.8.8.8:53              ESTABLISHED
udp        0      0 0.0.0.0:49355           0.0.0.0:*
udp        0      0 0.0.0.0:57548           0.0.0.0:*
udp        0      0 172.19.0.1:41165        172.19.0.2:53           ESTABLISHED
udp        0      0 0.0.0.0:41169           0.0.0.0:*
udp        0      0 0.0.0.0:45266           0.0.0.0:*
udp        0      0 0.0.0.0:57554           0.0.0.0:*
udp        0      0 172.19.0.1:45291        8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:33334        180.76.76.76:53         ESTABLISHED
udp        0      0 172.19.0.1:33393        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:29298        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:12939        180.76.76.76:53         ESTABLISHED
udp        0      0 172.19.0.1:12951        8.8.4.4:53              ESTABLISHED
udp        0      0 172.19.0.1:4913         172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:45891        172.19.0.2:53           ESTABLISHED
udp        0      0 0.0.0.0:37711           0.0.0.0:*
udp        0      0 172.19.0.1:25437        180.76.76.76:53         ESTABLISHED
udp        0      0 0.0.0.0:41850           0.0.0.0:*
udp        0      0 0.0.0.0:1133            0.0.0.0:*
udp        0      0 172.19.0.1:21659        180.76.76.76:53         ESTABLISHED
udp        0      0 172.19.0.1:25755        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:50333        180.76.76.76:53         ESTABLISHED
udp        0      0 0.0.0.0:58575           0.0.0.0:*
udp        0      0 172.19.0.1:17618        8.8.8.8:53              ESTABLISHED
udp        0      0 0.0.0.0:46315           0.0.0.0:*
udp        0      0 172.19.0.1:54510        180.76.76.76:53         ESTABLISHED
udp        0      0 172.19.0.1:9479         8.8.4.4:53              ESTABLISHED
udp        0      0 0.0.0.0:42251           0.0.0.0:*
udp        0      0 172.19.0.1:30024        8.8.8.8:53              ESTABLISHED
udp        0      0 172.19.0.1:17826        8.8.8.8:53              ESTABLISHED
udp        0      0 0.0.0.0:54703           0.0.0.0:*
udp        0      0 0.0.0.0:42620           0.0.0.0:*
udp        0      0 172.19.0.1:54911        8.8.8.8:53              ESTABLISHED
udp        0      0 0.0.0.0:42626           0.0.0.0:*
udp        0      0 0.0.0.0:54932           0.0.0.0:*
udp        0      0 172.19.0.1:14016        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:30407        172.19.0.2:53           ESTABLISHED
udp        0      0 0.0.0.0:59092           0.0.0.0:*
udp        0      0 172.19.0.1:46817        180.76.76.76:53         ESTABLISHED
udp        0      0 172.19.0.1:63224        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:22280        8.8.4.4:53              ESTABLISHED
udp        0      0 0.0.0.0:50956           0.0.0.0:*
udp        0      0 0.0.0.0:59158           0.0.0.0:*
udp        0      0 0.0.0.0:47002           0.0.0.0:*
udp        0      0 172.19.0.1:26523        180.76.76.76:53         ESTABLISHED
udp        0      0 0.0.0.0:59304           0.0.0.0:*
udp        0      0 172.19.0.1:59382        8.8.4.4:53              ESTABLISHED
udp6       0      0 :::33197                :::*
udp6       0      0 :::5684                 :::*
......

**Comment by yzou** [comment] 2020-01-21 16:33
It seems the DNS packet is not going through the tun device, but send out directly through the network.

**Comment by Mygod** [comment] 2020-01-21 17:15
@madeye It seems like [`BufferWriter_StartPacket`](https://github.com/shadowsocks/badvpn/blob/7bcb2e497a28244b8a9a880c1aa1c8037aa4b736/flow/BufferWriter.c#L75) returns 0 if `!o->out_have`, which I suspect means that the previous packet send has not completed?

**Comment by yzou** [comment] 2020-01-21 19:32
> @madeye It seems like [`BufferWriter_StartPacket`](https://github.com/shadowsocks/badvpn/blob/7bcb2e497a28244b8a9a880c1aa1c8037aa4b736/flow/BufferWriter.c#L75) returns 0 if `!o->out_have`, which I suspect means that the previous packet send has not completed?

@Mygod  I reviewed the code several times since 2017, you remind me about the previous not completed issue in the code [SocksUdpGwClient_SubmitPacket](https://github.com/shadowsocks/badvpn/blob/7bcb2e497a28244b8a9a880c1aa1c8037aa4b736/tun2socks/SocksUdpGwClient.c#L623)

1. If UDP client didn't find a conn, and the `o->num_connections` didn't reach the `o->max_connections`, then call `connection_init` to init a new conn, but will not call `connection_send` to submit the packet
2. I checked connection_init, it'll call a pending job `connection_first_job_handler`, in that job to call `connection_send`
3. In connection_init it also calls `BufferWriter_Init` to init `o->udp_send_writer`, and set `udp_send_writer->out_have` to 0
4. When the job is called, `BufferWriter_StartPacket` will check the `o->out_have`, and it's 0

So, the problem is, for a new connection, the first packet may never send out. I saw this "out of UDP buffer" issue for 3 years....

Why not call connection_send after `connection_init` instead of creating a job `connection_first_job_handler` to do this?
```
void SocksUdpGwClient_SubmitPacket(...)....
    // lookup connection
    SocksUdpGwClient_connection *con = find_connection(o, conaddr);

    // if no connection and can't create a new one, reuse the least recently used une
    if (!con && o->num_connections == o->max_connections) {
        con = reuse_connection(o, conaddr, is_dns);
    }

    if (!con) {
        // create new connection
        con = connection_init(o, conaddr, data, data_len, is_dns);
    } else {
        // reset remote addr
        con->conaddr.remote_addr = remote_addr;

        // move connection to front of the list
        LinkedList1_Remove(&o->connections_list, &con->connections_list_node);
        LinkedList1_Append(&o->connections_list, &con->connections_list_node);

        // send packet to existing connection
        connection_send(con, data, data_len);
    }
```

```
static SocksUdpGwClient_connection *connection_init(...)
    // init first job
    BPending_Init(&o->first_job, BReactor_PendingGroup(client->reactor), (BPending_handler)connection_first_job_handler, o);
......
    // init UDP writer
    BufferWriter_Init(&o->udp_send_writer, client->udp_mtu, BReactor_PendingGroup(client->reactor));
...
```

**Comment by madeye** [comment] 2020-01-21 21:54
Yeah, I think @yzou is right. But it's not clear to me why tun2socks implemented this in the first place.

**Comment by madeye** [comment] 2020-01-21 22:11
Try 315e56c.

**Comment by Mygod** [comment] 2020-01-22 05:10
Debug build artifacts: https://circleci.com/gh/shadowsocks/shadowsocks-android/408#artifacts

**Comment by yzou** [comment] 2020-01-22 06:34
> Yeah, I think @yzou is right. But it's not clear to me why tun2socks implemented this in the first place.

I think it's because the original badvpn implementation of UDP is sock5 protocol, for new UDP session, a TCP session of UDP_ASSOCIATE is needed to create first, so the first job is needed to send the first packet after the TCP session is created.

**Comment by yzou** [comment] 2020-01-22 06:36
> Try [315e56c](https://github.com/shadowsocks/shadowsocks-android/commit/315e56c69ba144a58236f002db135815486dcf9c).

The fix didn't set `o->out_have` to 1 in connection_init, and then connection_send will fail again. I'm wonder when the `o->out_have` is set to 1, with conn or without conn.

**Comment by madeye** [comment] 2020-01-22 11:40
I reviewed the code again. The previous code by @linusyang is correct.

Badvpn follows an aync buffer allocation approach, so we need to send the first packet after the buffer is allocated successfully. That's why we need to submit first packet into the reactor (event loop).

One possible missing thing is that if the associated socket of a UDP connection is closed by system, it's possible that the `out_have` never got reset, which means previous packet hasn't been sent out.

I'm trying to reproduce the behavior assumed above. However, after hours, I didn't see any errors on my Huawei phone.

Here is another debug APK with a local fix, you may want to have a try: https://www.dropbox.com/s/agysooj5bxmu083/shadowsocks-2414.apk

**Comment by yzou** [comment] 2020-01-22 13:04
> Try [315e56c](https://github.com/shadowsocks/shadowsocks-android/commit/315e56c69ba144a58236f002db135815486dcf9c).

This change will cause a crash sometimes.

At the end of connection_send in [
ed3c769](https://github.com/shadowsocks/shadowsocks-android/commit/ed3c7694ffefc36825e064c7fe1a98d84bb9af03) it should return 0 as its return type changes from void to int

**Comment by madeye** [comment] 2020-01-22 13:16
Yeah, we should return 0 here. But I don't think it would cause any crash. Can you submit the crash log?

**Comment by yzou** [comment] 2020-01-22 13:27
@madeye I mean the old change, I set a 1 to out_have after connection_init.....

**Comment by yzou** [comment] 2020-01-22 16:20
I saw only one start log of tun2socks, no log output from tun2socks.

> 2020-01-23 00:16:36.189 15073-15073/com.github.shadowsocks:bg D/GuardedProcessPool: start process: /data/app/com.github.shadowsocks-d5EVyPNTNrNK2xszjHEU0A==/lib/arm64/libtun2socks.so --netif-ipaddr 172.19.0.2 --socks-server-addr 127.0.0.1:1080 --tunmtu 1500 --sock-path sock_path --dnsgw 127.0.0.1:5450 --loglevel warning --netif-ip6addr fdfe:dcba:9876::2 --enable-udprelay

Btw, I think the IP addresses should swap between tun and tun2socks, as the tun is the client and IP should be 172.19.0.2, tun2socks is the router and IP should be 172.19.0.1.

**Comment by yzou** [comment] 2020-01-23 18:28
> I don't think it's related to tun2socks.
> 
> From your description, it looks that the local resolver got stuck. That explains why Telegram still works, which connects to IPs directly. @Mygod what do you think?
> 
> I cannot reproduce this issue with the same EMUI version. You may also try this https://club.huawei.com/thread-21446964-1-1.html

The "out of UDP buffer" happened again after keeping connected for one day, with "Auto Private DNS" option. Now I can't access service that needs DNS.

```
2020-01-24 02:26:56.365 23775-23775/? D/tun2socks: DEBUG(tun2socks): device: received packet
2020-01-24 02:26:56.365 23775-23775/? D/tun2socks: INFO(tun2socks): UDP: from device 40 bytes
2020-01-24 02:26:56.365 23775-23775/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-24 02:26:56.365 23775-23775/? D/tun2socks: DEBUG(BReactor): Calling epoll_wait
2020-01-24 02:26:56.515 23775-23775/? D/tun2socks: DEBUG(BReactor): epoll_wait returned 1 file descriptors
2020-01-24 02:26:56.515 23775-23775/? D/tun2socks: DEBUG(BReactor): Dispatching file descriptor
2020-01-24 02:26:56.515 23775-23775/? D/tun2socks: DEBUG(tun2socks): device: received packet
2020-01-24 02:26:56.516 23775-23775/? D/tun2socks: INFO(tun2socks): UDP: from device 43 bytes
2020-01-24 02:26:56.516 23775-23775/? D/tun2socks: ERROR(SocksUdpGwClient): out of UDP buffer
2020-01-24 02:26:56.516 23775-23775/? D/tun2socks: DEBUG(BReactor): Calling epoll_wait
2020-01-24 02:26:56.562 23775-23775/? D/tun2socks: DEBUG(BReactor): epoll_wait timed out
2020-01-24 02:26:56.563 23775-23775/? D/tun2socks: DEBUG(BReactor): Dispatching timer
2020-01-24 02:26:56.563 23775-23775/? D/tun2socks: DEBUG(tun2socks): TCP timer
```

**Comment by yzou** [comment] 2020-01-23 18:38
I saw some strange UDP sessions when the "out of UDP buffer" issue occured (UDP DNS option is enable):

```
udp        0      0 172.19.0.1:63152        172.19.0.2:53           ESTABLISHED
udp        0      0 172.19.0.1:24055        180.76.76.76:53         ESTABLISHED
udp        0      0 172.19.0.1:12590        180.76.76.76:53         ESTABLISHED
udp        0      0 172.19.0.1:63152        172.19.0.2:53           ESTABLISHED
```

I guess it may be an issue in some condition, the tun2socks or ss-local send out DNS packets with the wrong address and causes a packet loop. Even the phone goes to sleep, the packet is continually sending out.

**Comment by madeye** [comment] 2020-01-23 23:00
@yzou From your log, it looks that you didn't use the latest code. After "out of UDP buffer", we should see logs for new connection creation.

**Comment by yzou** [comment] 2020-01-25 17:12
> Yeah, we should return 0 here. But I don't think it would cause any crash. Can you submit the crash log?

I din't find coredump files in /data/, should I enable core dump manually?

**Comment by madeye** [comment] 2020-01-26 01:02
Just try the latest release here: https://github.com/shadowsocks/shadowsocks-android/releases/tag/v5.0.3

**Comment by yzou** [comment] 2020-01-26 09:32
I have tun2socks crashes, I created a pull request to help debug crashes.
https://github.com/shadowsocks/badvpn/pulls

**Comment by madeye** [comment] 2020-01-26 09:51
I think you need to open a new issue now. 

It's not clear how to reproduce the crash you mentioned in the latest comments.

Closing the issue as it's obsolete now.

**Closed by madeye** 2020-01-26 09:51 UTC
Labels: bug
