### ISSUE TITLE
IPv6 DNS resolution problem: no AAAA records

### ISSUE THREAD

**Issue by xubin990510** [shadowsocks/shadowsocks-android#868] opened 2016-09-07 12:22 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Shadowsocks are you using?

3.0.8 from Google Play.

The server uses shadowsocks-libev 2.4.7 from Arch Linux.

### What Android OS version and device are you using?

Nexus 5 with Android 7.0 (NRD90M)

### What did you do?

Trying to access ipv6 sites (my server has ipv6 address)

Trying to use https://test-ipv6.com

### What did you expect to see?

The page loads normally.

I get a non-zero score on test-ipv6.com

### What did you see instead?

Sites are not accessible with error NXDOMAIN

test-ipv6.com says my DNS does not support AAAA records (but when I dig @[my DNS] [ipv6.google.com] I get the correct result)

![screenshot_20160907-200857](https://cloud.githubusercontent.com/assets/7804730/18311772/c0f42f34-74cb-11e6-84bb-e0d6f33e959e.png)

Also test-ipv6.com gives out my server's ipv6 address correctly and I'm able to access ipv6 sites if I type in IP directly. 
![screenshot_20160907-202040](https://cloud.githubusercontent.com/assets/7804730/18311755/ac6c79f4-74cb-11e6-983c-242b5b5d0e05.png)

### What is your config in detail (with all sensitive info masked)?

encryption: chacha20

UDP forwarding ON

IPv6 forwarding ON

Route Bypass LAN

Per-App proxy ON

KCP OFF

server side listening `[::0]` and `0.0.0.0` and extra  command line options: `-6 -u`

------

Thanks in advance.

**Comment by wongsyrone** [comment] 2016-09-07 12:26
It seems pdnsd doesn't enable IPv6, you can try my modified version to check if the issue still persist. https://github.com/wongsyrone/shadowsocks-android/releases

**Comment by xubin990510** [comment] 2016-09-07 12:36
@wongsyrone

Problem persists. Everything's exactly the same as above.

**Comment by wongsyrone** [comment] 2016-09-07 12:40
Can you find something like "successfully resolved" for IPv6 domains in your server log? ArchLinux's package uses libudns as system library, this may not compiled with IPv6 support

**Comment by wongsyrone** [comment] 2016-09-07 12:41
You can check this commit: https://github.com/shadowsocks/shadowsocks-libev/commit/446e570b7dd4f4651a0506a8d5c23e2115c099e7

**Comment by wongsyrone** [comment] 2016-09-07 12:43
Modify libudns's PKGBUILD and rebuild with IPv6 support should do the trick, you can find what you need via `./configure --help` in its tarball.

**Comment by madeye** [comment] 2016-09-07 12:46
Surprisingly, I can reproduce this issue on Android 7.0, but not on Android 6.0.

It seems a regression of IPv6 support of Google.

**Comment by xubin990510** [comment] 2016-09-07 12:48
@wongsyrone

>> Can you find something like "successfully resolved" for IPv6 domains in your server log? 

I can see lines like this: 

    INFO: resolving hostname to IPv6 address first

but not "successfully resolved" ones.

>> ArchLinux's package uses libudns as system library, this may not compiled with IPv6 support

Hmm, how can I check?

**Comment by xubin990510** [comment] 2016-09-07 12:51
@madeye 

Well, that's interesting.

I also remember everything worked just fine before I upgraded from Marshmallow to Nougat (sorry I forgot to mention that above).

**Comment by wongsyrone** [comment] 2016-09-07 12:51
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/shadowsocks-libev#n32
and
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/udns#n18

If it's Google's fault, we can do nothing but wait for next release.

**Comment by xubin990510** [comment] 2016-09-07 13:00
If it helps, test-ipv6.com says I have a working ipv6-supported DNS server if I switch off Shadowsocks. I can't access sites, though (my phone don't have an IPv6 address).

`dig @192.168.1.1 ipv6.google.com` looks fine.

**Comment by madeye** [comment] 2016-09-07 13:15
It turns out to be a bug of Chrome on Android 7.0. You may try Firefox instead, which works well on Android 7.0.

**Comment by xubin990510** [comment] 2016-09-07 13:24
@madeye 

Seems you are correct.. 

Chrome 52 and Chromium 51 all failed to resolve things correctly. Firefox operates fine, just as expected. 

And Chrome Dev (54) operates fine. 

So this seems like a bug in Chrome rather than shadowsocks-android.

**Comment by madeye** [comment] 2016-09-07 13:25
Cool, closing the bug.

**Closed by madeye** 2016-09-07 13:25 UTC

**Comment by xubin990510** [comment] 2016-09-07 13:30
😋 thanks a lot.
