### ISSUE TITLE
最新版本v4.6.4开obfs无法连接

### ISSUE THREAD

**Issue by polong** [shadowsocks/shadowsocks-android#2041] opened 2018-12-22 15:25 UTC
*Smartphone (please complete the following information):**
 - Android version: 7.0
 - Device: moto G4
 
**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open

最新版本v4.6.4
加密模式XCHACHA-IETF-POLY1305
用simple obfs插件tls混淆后无法连接，关掉这个混淆能正常连接

**Comment by madeye** [comment] 2018-12-23 01:00
Tried on local device, but couldn't reproduce the issue.

Try uninstall shadowsocks and simple-obfs, then reinstall them.

**Comment by Mygod** [comment] 2018-12-23 07:45
If you take a look at [diff between 4.6.3 and 4.6.4](https://github.com/shadowsocks/shadowsocks-android/compare/v4.6.3...v4.6.4), there is virtually no change to the core functionalities.

**Comment by polong** [comment] 2018-12-23 09:12
经过多次反复安装尝试，确实4.6.3能连接，4.6.4不能。

**Comment by zhangyz1997** [comment] 2018-12-23 10:36
I have upgraded from 4.5.7 and meet the same problem on my Mokee 8.1 (based on Android 8.1) device. No luck after reinstalling simple obfuscation and shadowsocks.

**Comment by Mygod** [comment] 2018-12-23 11:38
Attach logcat or other relevant information.

**Comment by polong** [comment] 2018-12-23 14:48
@Mygod 能力有限，实在不知道这个是不是您需要的，里面提供两个，4.6.3是能正常连接的，4.6.4是不能的，如果还不知原因，我只能老老实实呆在4.6.3了
[D.zip](https://github.com/shadowsocks/shadowsocks-android/files/2706031/D.zip)

**Comment by polong** [comment] 2018-12-23 14:58
在反复的4.6.3和4.6.4倒腾安装过程中发现一个奇怪的现象，一会儿配置列表变成在某一时间点之前的列表，之后添加的都没了，然后多弄几次整个列表都空了要重新添加，再多折腾几次那个某个时间点之前的列表又回来了，有人知道我在说什么吗？ 尴尬

**Comment by Mygod** [comment] 2018-12-23 16:31
@madeye Hmmm looks like ss-local is crashing.

**Comment by madeye** [comment] 2018-12-23 23:13
Which apk did you install? Arm or arm64?

The only difference between 4.6.3 and 4.6.4 is I updated NDK bundle.

**Comment by polong** [comment] 2018-12-24 01:01
@madeye Arm

**Comment by madeye** [comment] 2018-12-24 01:01
Please try this APK https://www.dropbox.com/s/5toqadvjqe469ex/mobile-universal-release.apk?dl=0

Which is built with NDK 16.1.

**Comment by madeye** [comment] 2018-12-24 01:02
@polong Also try arm64 APK instead

**Comment by Mygod** [comment] 2018-12-24 01:03
@madeye Which NDK bundle are you using? I'm still on r18b.

**Comment by madeye** [comment] 2018-12-24 01:04
@Mygod NDK 18.1. I think

**Comment by polong** [comment] 2018-12-24 01:06
@madeye 我无法安装64的，不兼容，你给的apk我也打不开

**Comment by madeye** [comment] 2018-12-24 01:08
Moto G4  is shipped with ARM A53 CPU cores, which should be compatible with ARM64 APKs.

**Comment by madeye** [comment] 2018-12-24 01:11
Hmm. according to https://forums.lenovo.com/t5/Moto-G4-Moto-G4-Plus-Moto-G4/Moto-G4-Plus-32bit-Processor/td-p/3337312

Moto G4 is using a 32-bit image...

**Comment by madeye** [comment] 2018-12-24 01:36
@polong Try this one: https://www.dropbox.com/s/g5iuekc03u2t05m/mobile-armeabi-v7a-release.apk

**Comment by polong** [comment] 2018-12-24 02:01
@madeye 一切正常了哦，谢谢

**Comment by madeye** [comment] 2018-12-24 02:03
@polong Please also help to try this one: https://www.dropbox.com/s/r6cdwjf8vq0necl/mobile-armeabi-v7a-release-ndk-18b.apk

**Comment by zhangyz1997** [comment] 2018-12-24 04:43
> @polong Please also help to try this one: https://www.dropbox.com/s/r6cdwjf8vq0necl/mobile-armeabi-v7a-release-ndk-18b.apk

This version works as expected. Thanks.

**Comment by madeye** [comment] 2018-12-24 04:54
Please try again with this one: https://www.dropbox.com/s/ejldd4g8pka4zjm/mobile-armeabi-v7a-release-ndk-r18b-2.apk?dl=0

@zhangyz1997

**Comment by zhangyz1997** [comment] 2018-12-24 05:00
> Please try again with this one: https://www.dropbox.com/s/ejldd4g8pka4zjm/mobile-armeabi-v7a-release-ndk-r18b-2.apk
> 
> @zhangyz1997

@madeye boommed with the same problem: connection closed by peer

**Comment by madeye** [comment] 2018-12-24 05:15
Verified on my local device. The binary built with NDK r18b will crash on any ARM64 device.

**Comment by Mygod** [comment] 2018-12-24 14:31
That's interesting. We should probably report this to Google?

**Comment by madeye** [comment] 2018-12-25 00:57
Let me understand the root cause first.

IMO, it's related to some auto vectorzing feature, which is causing alignment exception in vector instruction (NEON).

**Closed** 2018-12-25 01:34 UTC

**Comment by madeye** [comment] 2018-12-25 01:39
Okay, it's indeed related to the alignment.

Now we enforce the 16-byte alignment for the murmur hash function on 32-bit architecture.

**Comment by Mygod** [comment] 2018-12-26 09:37
Update: I just updated my NDK to 19.0.5160253 rc2 and it (without the fix) no longer crashes on ARM. Maybe let's just upgrade NDK instead.

**Comment by madeye** [comment] 2018-12-26 09:59
Great, but I'd like to keep the libcork fix here, in case we see regression in the future.

**Comment by Mygod** [comment] 2018-12-26 10:01
I, on the contrary, want to get rid of it. :sweat_smile:

**Comment by madeye** [comment] 2018-12-26 10:10
The alignment issue won't happen all the time. So I don't think Google fixed the bug but it just happens to work.

We cannot make sure if constant input string aligned to 8-byte address. If aggressive auto vectorization is enabled in tool chain, we would see the regression again.
