### ISSUE TITLE
kcp is not working

### ISSUE THREAD

**Issue by LiR1cky** [shadowsocks/shadowsocks-android#795] opened 2016-08-06 16:41 UTC
the symptom is from the server side there's no stream opened.
with same kcptun settings (parameter) the kcptun client works fine on my linux server/arm router, but while I enabled the KCP on shadowsocks-android 3.0.0/3.0.1, nothing happened from server side while I tail -f the kcptun.log.

Where can I find the log from the phone? Maybe I can get some clue from there.

PS: Parameter I'm using on both server side and client side are exactly the same as you suggested on release 3.0.0

**Comment by madeye** [comment] 2016-08-06 22:47
Post your parameters here.

**Comment by shutup** [comment] 2016-08-06 23:39
@madeye thx for your work,i also not make it work,the parameter i use is just ```--key xxx --mode fast2``` ,and the origin shadowsocks config is not changed,and with my kcptun_android app ,i can use kcptun with the same parameter in NAT mode.

**Comment by madeye** [comment] 2016-08-06 23:49
@shutup 

1. Could you try a smaller MTU, like `--mtu 1024`?

2. In VPN mode, after establishing the VPN connection, could you try turn on and off the airplane mode?

**Comment by madeye** [comment] 2016-08-06 23:49
@shutup Also, what's your Android version?

**Comment by shutup** [comment] 2016-08-07 00:04
@madeye i just try your advice,but still nothing happened,my phone is MIUI8 ,android 6.0.1 OS.

**Comment by madeye** [comment] 2016-08-07 00:22
@shutup What's your KCP port number? It should be the remote kcptun's port.

**Comment by madeye** [comment] 2016-08-07 00:23
Or maybe you can post all your configs here, masking your server IP and password.

**Comment by shutup** [comment] 2016-08-07 01:15
in my vps the kcptun config is 
<pre>
./server_linux_amd64 -l :554 -t 127.0.0.1:443 -key xxxxxx -mode fast2
</pre>
on my phone,the config  is 
<pre>
shadowsocks
server_ip:xxx.xxx.xxx.xxx
remote_port:443
local_port:1080
password:xxxx
encrypt:rc4-md5

kcptun
enable :true
port:554
parameter:--key xxxxxx --mode fast2
</pre>

**Comment by wang20150419** [comment] 2016-08-07 01:21
the kcptun config of my vps is :
server_linux_amd64 -l :37777 -t 127.0.0.1:7777  --crypt xor --key xxxxx --mtu 1400 --sndwnd 2048 --rcvwnd 2048 --mode fast2

the config of my huiwei mate8 is:
kcptun enable : true
port:37777
parameter:  --crypt xor --key xxxxx --mtu 1400 --sndwnd 2048 --rcvwnd 2048 --mode fast2

It doesn't work!

**Comment by codexss** [comment] 2016-08-07 01:27
with the same problem with @shutup 
my phone is nexus5 on android 6.0.1
the network is can not be used.

**Comment by madeye** [comment] 2016-08-07 01:28
Could you try `--crypt none --mtu 1024 --mode fast2`? You need set the parameters for both server and client.

**Comment by madeye** [comment] 2016-08-07 01:35
Also, have you enabled UDP Forwarding in shadowsocks?

**Comment by codexss** [comment] 2016-08-07 01:41
电脑上没什么问题

![5 _ii nwdl4 zqbvc n28c](https://cloud.githubusercontent.com/assets/5959201/17459957/e8fb69a4-5c82-11e6-8918-e5c7ef8b0213.png)
![d3 5w 9 y6 uytzttb](https://cloud.githubusercontent.com/assets/5959201/17459958/e9a2433c-5c82-11e6-8743-de3cc752be4e.png)
![image](https://cloud.githubusercontent.com/assets/5959201/17459965/04229cfc-5c83-11e6-88ff-1ba3824393e8.png)

手机上相同的配置上不去网
![kwk c8 0i z19pve83nmb](https://cloud.githubusercontent.com/assets/5959201/17459959/ec9d4f1e-5c82-11e6-9dff-94d500cba8f8.png)
另外udp转发并没有打开

**Comment by madeye** [comment] 2016-08-07 01:49
According to your `ps|grep` results, it seems that UDP forwarding is enabled. Could you double check?

Also, could you post `adb logcat -s GuardedProcess`?

**Comment by shutup** [comment] 2016-08-07 01:50
@madeye also not work at all,can you post your success config?
and i am sure  [Kcptun_android](https://github.com/shutup/Kcptun_android) is usable.

**Comment by madeye** [comment] 2016-08-07 01:54
@shutup I don't have any issue with `--crypt none --mtu 1024 --mode fast2`. 

Have you enabled UDP forwarding?

**Comment by LiR1cky** [comment] 2016-08-07 01:55
kcptun settings:
- server side:
./server_linux_386 -t "127.0.0.1:22" -l :443 -mtu 1024 -crypt none -nocomp -sndwnd 1024 -rcvwnd 1024 -mode fast

- RedMi Note3 (MIUI8 EU/5.1.1):
--crypt none --mtu 1024 --sndwnd 1024 --rcvwnd 1024 --mode fast --nocomp

No UDP forwarding enabled.

**Comment by shutup** [comment] 2016-08-07 01:59
@madeye i open the udp forward.
the logcat is here
<pre>
08-07 09:53:01.456  3333 25138 I GuardedProcess: start process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-local-vpn.conf, --acl, /data/user/0/com.github.shadowsocks/acl.list)
08-07 09:53:01.477  3333 25140 I GuardedProcess: start process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-local, -V, -U, -b, 127.0.0.1, -t, 600, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-local-udp-vpn.conf)
08-07 09:53:01.552  3333 25146 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 67, --tunmtu, 1500, --sock-path, /data/user/0/com.github.shadowsocks/sock_path, --loglevel, 3, --enable-udprelay)
08-07 09:53:02.572  3333 25253 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/kcptun, -r, xxx.xxx.xxx.xxx:554, -l, 127.0.0.1:1170, --path, /data/user/0/com.github.shadowsocks/protect_path, --key, test, , --mode, fast2)
</pre>

**Comment by codexss** [comment] 2016-08-07 02:15
logcat here
08-07 10:14:22.921 10158  1128 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/pdnsd, -c, /data/user/0/com.github.shadowsocks/pdnsd-vpn.conf)
08-07 10:14:22.975 10158  1130 I GuardedProcess: start process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-tunnel, -V, -t, 10, -b, 127.0.0.1, -L, 8.8.8.8:53, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-tunnel-vpn.conf)
08-07 10:14:23.020 10158  1140 I GuardedProcess: start process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-local-vpn.conf, --acl, /data/user/0/com.github.shadowsocks/acl.list)
08-07 10:14:23.201 10158  1150 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 46, --tunmtu, 1500, --sock-path, /data/user/0/com.github.shadowsocks/sock_path, --loglevel, 3, --dnsgw, 26.26.26.1:1133)
08-07 10:14:24.244 10158  1181 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/kcptun, -r, **.**.**.**:53, -l, 127.0.0.1:1170, --path, /data/user/0/com.github.shadowsocks/protect_path, --crypt, none, --key, l3n71n, --mode, fast2)

**Comment by codexss** [comment] 2016-08-07 02:41
软件重装之后重新配置了一下用nat模式可以连上了，但是vpn模式还是不行，希望可以解决一下vpn不能用的问题。

**Comment by madeye** [comment] 2016-08-07 02:46
Could you try this apk? https://drive.google.com/open?id=0B3YSrCJtFxYiZ0MxQW9pRk1ySVk

**Comment by Dibel** [comment] 2016-08-07 02:46
I found it worked with UDP forward enabled, but actually it's kcptun "via Shadowsocks" because the server log reveals that the client address is server itself. Without UDP forward enabled, I found nothing in the server log.

Logcat:
```
08-07 10:04:58.985 12356 15582 I GuardedProcess: start process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-local, -V, -b, 127.0.0.1, -t, 600, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-local-vpn.conf, --acl, /data/user/0/com.github.shadowsocks/acl.list)
08-07 10:04:58.990 12356 15584 I GuardedProcess: start process: ArrayBuffer(/data/user/0/com.github.shadowsocks/ss-local, -V, -U, -b, 127.0.0.1, -t, 600, -P, /data/user/0/com.github.shadowsocks, -c, /data/user/0/com.github.shadowsocks/ss-local-udp-vpn.conf)
08-07 10:04:59.066 12356 15587 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/tun2socks, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.0, --socks-server-addr, 127.0.0.1:1080, --tunfd, 107, --tunmtu, 1500, --sock-path, /data/user/0/com.github.shadowsocks/sock_path, --loglevel, 3, --enable-udprelay)
08-07 10:05:00.076 12356 15609 I GuardedProcess: start process: WrappedArray(/data/user/0/com.github.shadowsocks/kcptun, -r, SERVER_IP:53, -l, 127.0.0.1:1170, --path, /data/user/0/com.github.shadowsocks/protect_path, --sndwnd, 128, --rcvwnd, 1024, --mode, fast2)
```

**Comment by isbaseby** [comment] 2016-08-07 02:51
遇到相同的情况，同样的配置在Mac工作正常，在Android上只有NAT模式可以用，vpn模式提示DNS查找失败

**Comment by Dibel** [comment] 2016-08-07 02:53
@madeye confirmed working on VPN mode without UDP forward enabled, and server log shows the remote address is client IP. Thanks!

**Comment by codexss** [comment] 2016-08-07 02:54
@madeye 看起来像是工作正常了，WIFI/3G没发现问题

**Comment by madeye** [comment] 2016-08-07 02:56
Great! Thanks for your effort. It's a regression since 3.0.1. Fixed via https://github.com/shadowsocks/shadowsocks-android/commit/4817539ca2ebd3bdefc0fb13f4d638970ff397e1

Closing the bug.

**Closed by madeye** 2016-08-07 02:56 UTC

**Comment by LiR1cky** [comment] 2016-08-07 03:07
working fine on 3.0.2！ Thanks.

**Comment by shutup** [comment] 2016-08-07 03:10
great work,thx!

**Comment by oyrx** [comment] 2016-08-07 03:24
感谢
