### ISSUE TITLE
未知插件obfs-local

### ISSUE THREAD

**Issue by mcmxciv** [shadowsocks/shadowsocks-android#1428] opened 2017-10-25 01:22 UTC
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version:  "7.0" *
* Device: * Huawei Mate 9*
* Shadowsocks version: *version code "v3.1.0" *
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:chacha20-ietf-poly1305
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS Forwarding
* Plugin configuration (if applicable):
Simple obfuscation
obfs-host=www.189.cn;obfs=tls
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

When open Android client,it report:后台服务启动失败：无法连接远程服务器：未知插件obfs-local
但只要打开配置，重新配置一下，就能正常打开。

**Comment by chenyue404** [comment] 2017-10-25 01:27
插件的后台自启动打开

**Comment by madeye** [comment] 2017-10-25 02:56
Duplicate of https://github.com/shadowsocks/shadowsocks-android/issues/1091#issuecomment-288420797

**Closed** 2017-10-25 02:56 UTC

**Comment by mcmxciv** [comment] 2017-10-25 02:59
bingo，问题解决

**Comment by baibinghere** [comment] 2021-03-15 07:15
这个问题困扰了我很久，谢谢解释！

**Comment by guangkeli** [comment] 2023-01-29 06:03
后台自启动是打开的，配置也是一样，还是不行

**Comment by lvan100** [comment] 2024-02-18 06:24
> 插件的后台自启动打开

如果是华为手机，把启动的「自动管理」关掉，改为「手动管理」
