### ISSUE TITLE
DNS bugs on 5.13 pls fix it.

### ISSUE THREAD

**Issue by shell12345** [shadowsocks/shadowsocks-android#2576] opened 2020-08-24 11:02 UTC
Please read contributing guidelines. Thanks.

**Describe the bug**
unable to resolve hostname with smartDNS  on remote server on 5.13.
but 5.12 is fine.
smartDNS listen to udp DNS request on 53.
also 
smartDNS listen to tcp DNS request on 53.
**To Reproduce**
1. 5.1.3
2. remote server uses smartDNS or dnsmsq to unlock stream, like Netflix
3. set remote DNS 127.0.0.1 or 0.0.0.0
4. VPN mode 
5. unable to resolve hostname

**Expected behavior**
5.12 and below works fine with the mentioned process. 
And 5.13 can not resolve DNS no matter set remote DNS to 0.0.0.0/127.0.0.1 or 8.8.8.8/1.1.1.1 .
pls, fix it.
**Smartphone (please complete the following information):**
 - Android 10
 - Device:  Google Pixel 3 XL
 - Last version 

**Configuration**
Put an `x` inside the [ ] that applies.

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 127.0.0.1 or 0.0.0.0
* [ x] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open

**Comment by shell12345** [comment] 2020-08-24 11:04
relate issue
#2564
I think you remove the DNS forward through udp.
However, the DNS forward through tcp also failed.

**Comment by madeye** [comment] 2020-08-24 11:32
Cannot reproduce locally.

In fact, nothing changed in DNS module from 5.1.2 to 5.1.3.

**Comment by Mygod** [comment] 2020-08-24 15:55
Logcat?

**Comment by shell12345** [comment] 2020-08-25 01:57
Hi, @Mygod , @madeye 
how can I export the local logcat from ss?

5.13 with the same profile and clean install
![Screenshot_20200825-094603-01](https://user-images.githubusercontent.com/46412851/91113842-11c9d680-e6b9-11ea-986f-597740df6036.jpeg)

5.12 with KCPTUN plugin
![Screenshot_20200825-095145-01](https://user-images.githubusercontent.com/46412851/91113846-142c3080-e6b9-11ea-98b1-8c65803f6638.jpeg)

**Comment by shell12345** [comment] 2020-08-25 01:58
what goes wrong?

**Comment by madeye** [comment] 2020-08-25 02:04
The kcptun plugin looks out of date, nothing wrong with the DNS logic.

**Comment by madeye** [comment] 2020-08-25 02:42
Try this kcptun apk

[kcptun-arm64-v8a-1.0.1.apk.zip](https://github.com/shadowsocks/shadowsocks-android/files/5121095/kcptun-arm64-v8a-1.0.1.apk.zip)

**Comment by Mygod** [comment] 2020-08-25 04:01
We can use the plugin version code to identify legacy behavior. @madeye

**Comment by shell12345** [comment] 2020-08-25 11:01
Thanks, everyone.
This is the kcptun plugin bug.

Blew fix it.
> Try this kcptun apk
> 
> [kcptun-arm64-v8a-1.0.1.apk.zip](https://github.com/shadowsocks/shadowsocks-android/files/5121095/kcptun-arm64-v8a-1.0.1.apk.zip)

**Comment by kn007** [comment] 2020-09-25 11:59
Same issue here.
Fixed with new kcptun plugin apk.

> Try this kcptun apk
> 
> [kcptun-arm64-v8a-1.0.1.apk.zip](https://github.com/shadowsocks/shadowsocks-android/files/5121095/kcptun-arm64-v8a-1.0.1.apk.zip)

**Comment by kn007** [comment] 2020-09-25 12:00
V2ray plugin have same problem with 5.13

**Comment by gregist** [comment] 2020-09-25 15:09
> V2ray plugin have same problem with 5.13
> 
> I think #2582 is the same problem

If so plz reopen this issue.

Is there any temporary workaround for this problem?

**Comment by IronXiao** [comment] 2020-10-01 10:07
Will you update the simple-obfs-android apk since simple-obfs has have the same issue with the new version 5.1.3.

**Comment by Mygod** [comment] 2020-10-01 19:20
> We can use the plugin version code to identify legacy behavior. @madeye

@madeye How about only using the new behavior for plugin 1.4.+?

Also we should do a new release with this fix: https://github.com/shadowsocks/shadowsocks-rust/commit/5af929004e3bef4d330de277de8a3fb32ce961b3

**Comment by madeye** [comment] 2020-10-01 22:02
@Mygod Not sure how to do that. Can you submit a pull request?

Yeah, we can schedule a release this week.

**Comment by Mygod** [comment] 2020-10-02 00:13
You can try to look at the app's metadata?

**Comment by madeye** [comment] 2020-10-02 00:20
It seems not possible to me, since we need to modify shadowsocks-rust to pass `-V` in command line if the plugin version is lower than v1.4.

**Comment by madeye** [comment] 2020-10-02 00:23
@Mygod do we have an API in PluginManager to retrieve the plugin version number?

**Comment by Mygod** [comment] 2020-10-02 00:23
Yes.

**Comment by madeye** [comment] 2020-10-02 00:33
Okay, please help me on this. I'm not familiar with this part of code.

I guess we can fallback to pass `-V` to the plugin if the plugin version < 1.4

**Comment by skyred** [comment] 2020-10-18 04:40
@madeye The latest version of Kcptun on Google Play store is 1.0.0, would you mind publishing the above newer version onto Play store?

**Comment by Darnix** [comment] 2020-10-19 04:02
Same issues here with v2ray-plugin 1.3.2. I checked [v2ray-plugin-android](https://github.com/shadowsocks/v2ray-plugin-android) but no update yet. Will there any update with it soon?

**Comment by madeye** [comment] 2020-10-20 02:21
@skyred Join the beta channel or download the apk directly from here: https://github.com/shadowsocks/kcptun-android/releases/tag/v1.0.1

**Comment by skyred** [comment] 2020-10-20 02:43
> @skyred Join the beta channel or download the apk directly from here: https://github.com/shadowsocks/kcptun-android/releases/tag/v1.0.1

Thanks. I didn't realize there was a beta program for KCPTUN, just joined, and it works!

**Closed** 2020-10-20 08:07 UTC
Labels: third-party bug
