### ISSUE TITLE
按完“常见问题”，不选择浏览器，按“关于”不会有东西出来

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#1487] opened 2017-12-07 01:04 UTC
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: android O "OPR5.170623.011"
* Device: nexus 6p
* Shadowsocks version: 4.3.2
* Last version that did not exhibit the issue (if applicable):
没测试
### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
按“常见问题”，弹出选择浏览器的提示(因为装了两个浏览器)，按返回，再按“关于”或者“常见问题”都不会有反应。

**Comment by iKirby** [comment] 2017-12-07 01:20
Can reproduce this on my device. I have only one browser installed, so this is not because of the choose browser dialog.
If you click "About" first, then it does nothing if you click "FAQ" without going back to the previous screen.

**Comment by Mygod** [comment] 2017-12-08 06:13
Fixed in beta branch.

**Closed by Mygod** 2017-12-08 06:13 UTC
Labels: bug, good first issue
