### ISSUE TITLE
4.5.5出现DNS错误

### ISSUE THREAD

**Issue by triaqu** [shadowsocks/shadowsocks-android#1740] opened 2018-04-09 01:28 UTC
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 8.1
* Device: Oneplus 5
* Shadowsocks version: 4.5.5 服务器端为最新版本
* Last version that did not exhibit the issue (if applicable):
4.5.3.
### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: aes-128-gcm
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x ] DNS Forwarding
* Plugin configuration (if applicable):
* [x ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
如果任意连接一个错误的配置后，切换到其他正常的配置。

### What did you expect to see?
能正常使用。

### What did you see instead?
切换到正常配置后也无网络连接，无论是否使用远程DNS是否使用obfs, 都会出现无法解析谷歌地址的错误。

开关不起作用，需要杀掉进程后重启才能使用。

**Comment by madeye** [comment] 2018-04-09 01:46
I cannot reproduce your issue locally.

It looks a known issue of Oneplus' latest ROM that it wouldn't flush DNS cache when VPN connection established or disconnected. https://github.com/shadowsocks/shadowsocks-android/issues/1721#issuecomment-379121367

**Comment by triaqu** [comment] 2018-04-09 02:07
@madeye  谢谢解答，但有个疑问，4.5.3版本确可以使用正常使用。

**Comment by Love4Taylor** [comment] 2018-04-09 03:26
@madeye 4.5.5, Google Pixel, Android P 有同样的问题, 当某一个配置文件连不上之后不管换成哪个都是无速度无响应, 杀进程后才可恢复

**Comment by madeye** [comment] 2018-04-09 04:34
@Love4Taylor Submit the output of `adb shell ps` and `adb logcat -s shadowsocks` here, after you reproduce the issue.

**Comment by Mygod** [comment] 2018-04-09 04:37
@madeye Interestingly, I noticed a similar bug as this one with #1742. Here's related log:

```
E/shadowsocks: getaddrinfo: No address associated with hostname
com.github.shadowsocks:bg W/GuardedProcess: process exit too fast, stop guard: /data/app/com.github.shadowsocks-o1SSyznkSJWlASYhjeATcw==/lib/arm64/libss-local.so -u -b 127.0.0.1 -l 1080 -t 600 -c /data/user/0/com.github.shadowsocks/files/shadowsocks.conf --fast-open
```

A git bisect shows that this is the first bad commit: https://github.com/shadowsocks/shadowsocks-libev/commit/5fa98a669312bf7e4271bc125581138551974ddf

**Comment by madeye** [comment] 2018-04-09 04:43
I think we only pass IP address to ss-local, right? Otherwise, we would see this kind to error.

**Comment by Mygod** [comment] 2018-04-09 05:03
@madeye The actual error is:

```
shadowsocks: bind: Address already in use
shadowsocks: bind() error
```

And it seems like this only happens after using an unusable config and there's an active connection. I think these are two unrelated bugs.

**Comment by triaqu** [comment] 2018-04-09 05:07
@madeye  
具体操作是已正常连接，测试网络后，切换了错误配置，测试网络报错，切换到正确配置，测试网络报错。
--------- beginning of system
--------- beginning of main
04-09 12:36:03.532 27096 27096 E shadowsocks: getpeername: Transport endpoint is not connected
04-09 12:36:19.913 27096 27096 E shadowsocks: getpeername: Transport endpoint is not connected
04-09 12:36:19.913 27096 27096 E shadowsocks: remote_recv_cb_recv: Software caused connection abort
04-09 12:36:19.913 27096 27096 E shadowsocks: remote_recv_cb_recv: Software caused connection abort
04-09 12:36:19.913 27096 27096 E shadowsocks: getpeername: Transport endpoint is not connected
04-09 12:36:19.914 27096 27096 E shadowsocks: getpeername: Transport endpoint is not connected
04-09 12:36:19.914 27096 27096 E shadowsocks: remote_recv_cb_recv: Software caused connection abort
04-09 12:36:19.914 27096 27096 E shadowsocks: remote_recv_cb_recv: Software caused connection abort
04-09 12:36:19.914 27096 27096 E shadowsocks: getpeername: Transport endpoint is not connected
04-09 12:36:19.914 27096 27096 E shadowsocks: remote_recv_cb_recv: Software caused connection abort
04-09 12:36:19.935 27096 27096 E shadowsocks: fast_open_connect: Network is unreachable
04-09 12:36:19.952 27096 27096 E shadowsocks: fast_open_connect: Network is unreachable
04-09 12:36:19.957 27096 27096 E shadowsocks: fast_open_connect: Network is unreachable
04-09 12:36:19.960 27096 27096 E shadowsocks: fast_open_connect: Network is unreachable
04-09 12:36:19.968 27096 27096 E shadowsocks: fast_open_connect: Network is unreachable
04-09 12:36:19.971 27096 27096 E shadowsocks: fast_open_connect: Network is unreachable
04-09 12:36:19.980 27096 27096 E shadowsocks: fast_open_connect: Network is unreachable
04-09 12:36:19.988 27096 27096 E shadowsocks: fast_open_connect: Network is unreachable
04-09 12:36:19.996 27096 27096 E shadowsocks: fast_open_connect: Network is unreachable
04-09 12:36:20.004 27096 27096 E shadowsocks: fast_open_connect: Network is unreachable
04-09 12:36:20.007 27096 27096 E shadowsocks: [udp] server_recv_sendto: Network is unreachable
04-09 12:37:05.934 27096 27096 E shadowsocks: remote_recv_cb_recv: Software caused connection abort
04-09 12:37:05.935 27096 27096 E shadowsocks: remote_recv_cb_recv: Software caused connection abort
04-09 12:37:05.935 27096 27096 E shadowsocks: remote_recv_cb_recv: Software caused connection abort
04-09 12:40:30.645 27096 27096 E shadowsocks: getpeername: Transport endpoint is not connected
04-09 12:47:41.231 27096 27096 E shadowsocks: remote_recv_cb_recv: Connection reset by peer
04-09 12:55:03.930 31289 31289 D shadowsocks: initializing acl...
04-09 12:55:03.968 31289 31289 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 12:55:03.968 31289 31289 D shadowsocks: using tcp fast open
04-09 12:55:03.968 31289 31289 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:55:03.968 31289 31289 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:55:03.968 31289 31289 D shadowsocks: udprelay enabled
04-09 12:55:32.430 31360 31360 D shadowsocks: initializing acl...
04-09 12:55:32.518 31360 31360 D shadowsocks: using tcp fast open
04-09 12:55:32.518 31360 31360 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:55:32.519 31360 31360 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:55:32.519 31360 31360 D shadowsocks: udprelay enabled
04-09 12:55:43.770 31429 31429 D shadowsocks: initializing acl...
04-09 12:55:43.809 31429 31429 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 12:55:43.809 31429 31429 D shadowsocks: using tcp fast open
04-09 12:55:43.809 31429 31429 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:55:43.809 31429 31429 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:55:43.809 31429 31429 D shadowsocks: udprelay enabled
04-09 12:55:55.506 31474 31474 D shadowsocks: initializing acl...
04-09 12:55:55.595 31474 31474 D shadowsocks: using tcp fast open
04-09 12:55:55.595 31474 31474 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:55:55.595 31474 31474 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:55:55.595 31474 31474 E shadowsocks: bind: Address already in use
04-09 12:55:55.595 31474 31474 E shadowsocks: bind() error
04-09 12:56:29.686 31532 31532 D shadowsocks: initializing acl...
04-09 12:56:29.782 31532 31532 D shadowsocks: using tcp fast open
04-09 12:56:29.782 31532 31532 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:56:29.782 31532 31532 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:56:29.782 31532 31532 E shadowsocks: bind: Address already in use
04-09 12:56:29.782 31532 31532 E shadowsocks: bind() error
04-09 12:58:26.215 31821 31821 D shadowsocks: initializing acl...
04-09 12:58:26.307 31821 31821 D shadowsocks: using tcp fast open
04-09 12:58:26.307 31821 31821 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:58:26.307 31821 31821 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:58:26.307 31821 31821 D shadowsocks: udprelay enabled
04-09 12:58:58.916 31821 31821 E shadowsocks: getpeername: Transport endpoint is not connected
04-09 12:59:20.818 31942 31942 D shadowsocks: initializing acl...
04-09 12:59:20.897 31942 31942 D shadowsocks: using tcp fast open
04-09 12:59:20.897 31942 31942 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:59:20.897 31942 31942 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:59:20.897 31942 31942 D shadowsocks: udprelay enabled
04-09 12:59:28.164 31992 31992 D shadowsocks: initializing acl...
04-09 12:59:28.200 31992 31992 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 12:59:28.200 31992 31992 D shadowsocks: using tcp fast open
04-09 12:59:28.200 31992 31992 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:59:28.201 31992 31992 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:59:28.201 31992 31992 D shadowsocks: udprelay enabled
04-09 12:59:37.751 32037 32037 D shadowsocks: initializing acl...
04-09 12:59:37.840 32037 32037 D shadowsocks: using tcp fast open
04-09 12:59:37.840 32037 32037 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:59:37.840 32037 32037 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:59:37.840 32037 32037 E shadowsocks: bind: Address already in use
04-09 12:59:37.840 32037 32037 E shadowsocks: bind() error
04-09 13:00:00.026 32087 32087 D shadowsocks: initializing acl...
04-09 13:00:00.053 32087 32087 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 13:00:00.053 32087 32087 D shadowsocks: using tcp fast open
04-09 13:00:00.054 32087 32087 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:00:00.054 32087 32087 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:00:00.054 32087 32087 E shadowsocks: bind: Address already in use
04-09 13:00:00.054 32087 32087 E shadowsocks: bind() error
04-09 13:00:21.960 32294 32294 D shadowsocks: initializing acl...
04-09 13:00:22.010 32294 32294 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 13:00:22.011 32294 32294 D shadowsocks: using tcp fast open
04-09 13:00:22.011 32294 32294 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:00:22.011 32294 32294 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:00:22.011 32294 32294 D shadowsocks: udprelay enabled
04-09 13:00:31.696 32350 32350 D shadowsocks: initializing acl...
04-09 13:00:31.774 32350 32350 D shadowsocks: using tcp fast open
04-09 13:00:31.774 32350 32350 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:00:31.774 32350 32350 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:00:31.774 32350 32350 D shadowsocks: udprelay enabled
04-09 13:02:41.545 32508 32508 D shadowsocks: initializing acl...
04-09 13:02:41.581 32508 32508 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 13:02:41.581 32508 32508 D shadowsocks: using tcp fast open
04-09 13:02:41.581 32508 32508 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:02:41.581 32508 32508 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:02:41.581 32508 32508 D shadowsocks: udprelay enabled
04-09 13:03:10.453 32578 32578 D shadowsocks: initializing acl...
04-09 13:03:10.536 32578 32578 D shadowsocks: using tcp fast open
04-09 13:03:10.536 32578 32578 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:03:10.536 32578 32578 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:03:10.536 32578 32578 E shadowsocks: bind: Address already in use
04-09 13:03:10.536 32578 32578 E shadowsocks: bind() error

**Comment by Mygod** [comment] 2018-04-09 05:14
@madeye Okay I think the problem is that `libss-local.so` is not responding to sigterm for some reason.

**Comment by triaqu** [comment] 2018-04-09 05:17
上面连接的配置文件没使用插件。

**Comment by triaqu** [comment] 2018-04-09 05:34
@Mygod  

4.5.3的cat log,操作是测了两次正常连接，切换到错误连接测两次，再切换到正确配置测两次。

`--------- beginning of system
--------- beginning of main
04-09 12:55:03.930 31289 31289 D shadowsocks: initializing acl...
04-09 12:55:03.968 31289 31289 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 12:55:03.968 31289 31289 D shadowsocks: using tcp fast open
04-09 12:55:03.968 31289 31289 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:55:03.968 31289 31289 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:55:03.968 31289 31289 D shadowsocks: udprelay enabled
04-09 12:55:32.430 31360 31360 D shadowsocks: initializing acl...
04-09 12:55:32.518 31360 31360 D shadowsocks: using tcp fast open
04-09 12:55:32.518 31360 31360 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:55:32.519 31360 31360 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:55:32.519 31360 31360 D shadowsocks: udprelay enabled
04-09 12:55:43.770 31429 31429 D shadowsocks: initializing acl...
04-09 12:55:43.809 31429 31429 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 12:55:43.809 31429 31429 D shadowsocks: using tcp fast open
04-09 12:55:43.809 31429 31429 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:55:43.809 31429 31429 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:55:43.809 31429 31429 D shadowsocks: udprelay enabled
04-09 12:55:55.506 31474 31474 D shadowsocks: initializing acl...
04-09 12:55:55.595 31474 31474 D shadowsocks: using tcp fast open
04-09 12:55:55.595 31474 31474 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:55:55.595 31474 31474 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:55:55.595 31474 31474 E shadowsocks: bind: Address already in use
04-09 12:55:55.595 31474 31474 E shadowsocks: bind() error
04-09 12:56:29.686 31532 31532 D shadowsocks: initializing acl...
04-09 12:56:29.782 31532 31532 D shadowsocks: using tcp fast open
04-09 12:56:29.782 31532 31532 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:56:29.782 31532 31532 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:56:29.782 31532 31532 E shadowsocks: bind: Address already in use
04-09 12:56:29.782 31532 31532 E shadowsocks: bind() error
04-09 12:58:26.215 31821 31821 D shadowsocks: initializing acl...
04-09 12:58:26.307 31821 31821 D shadowsocks: using tcp fast open
04-09 12:58:26.307 31821 31821 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:58:26.307 31821 31821 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:58:26.307 31821 31821 D shadowsocks: udprelay enabled
04-09 12:58:58.916 31821 31821 E shadowsocks: getpeername: Transport endpoint is not connected
04-09 12:59:20.818 31942 31942 D shadowsocks: initializing acl...
04-09 12:59:20.897 31942 31942 D shadowsocks: using tcp fast open
04-09 12:59:20.897 31942 31942 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:59:20.897 31942 31942 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:59:20.897 31942 31942 D shadowsocks: udprelay enabled
04-09 12:59:28.164 31992 31992 D shadowsocks: initializing acl...
04-09 12:59:28.200 31992 31992 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 12:59:28.200 31992 31992 D shadowsocks: using tcp fast open
04-09 12:59:28.200 31992 31992 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:59:28.201 31992 31992 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:59:28.201 31992 31992 D shadowsocks: udprelay enabled
04-09 12:59:37.751 32037 32037 D shadowsocks: initializing acl...
04-09 12:59:37.840 32037 32037 D shadowsocks: using tcp fast open
04-09 12:59:37.840 32037 32037 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 12:59:37.840 32037 32037 D shadowsocks: listening at 127.0.0.1:1080
04-09 12:59:37.840 32037 32037 E shadowsocks: bind: Address already in use
04-09 12:59:37.840 32037 32037 E shadowsocks: bind() error
04-09 13:00:00.026 32087 32087 D shadowsocks: initializing acl...
04-09 13:00:00.053 32087 32087 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 13:00:00.053 32087 32087 D shadowsocks: using tcp fast open
04-09 13:00:00.054 32087 32087 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:00:00.054 32087 32087 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:00:00.054 32087 32087 E shadowsocks: bind: Address already in use
04-09 13:00:00.054 32087 32087 E shadowsocks: bind() error
04-09 13:00:21.960 32294 32294 D shadowsocks: initializing acl...
04-09 13:00:22.010 32294 32294 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 13:00:22.011 32294 32294 D shadowsocks: using tcp fast open
04-09 13:00:22.011 32294 32294 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:00:22.011 32294 32294 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:00:22.011 32294 32294 D shadowsocks: udprelay enabled
04-09 13:00:31.696 32350 32350 D shadowsocks: initializing acl...
04-09 13:00:31.774 32350 32350 D shadowsocks: using tcp fast open
04-09 13:00:31.774 32350 32350 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:00:31.774 32350 32350 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:00:31.774 32350 32350 D shadowsocks: udprelay enabled
04-09 13:02:41.545 32508 32508 D shadowsocks: initializing acl...
04-09 13:02:41.581 32508 32508 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 13:02:41.581 32508 32508 D shadowsocks: using tcp fast open
04-09 13:02:41.581 32508 32508 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:02:41.581 32508 32508 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:02:41.581 32508 32508 D shadowsocks: udprelay enabled
04-09 13:03:10.453 32578 32578 D shadowsocks: initializing acl...
04-09 13:03:10.536 32578 32578 D shadowsocks: using tcp fast open
04-09 13:03:10.536 32578 32578 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:03:10.536 32578 32578 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:03:10.536 32578 32578 E shadowsocks: bind: Address already in use
04-09 13:03:10.536 32578 32578 E shadowsocks: bind() error
04-09 13:04:39.779 32691 32691 D shadowsocks: initializing acl...
04-09 13:04:39.818 32691 32691 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 13:04:39.818 32691 32691 D shadowsocks: using tcp fast open
04-09 13:04:39.818 32691 32691 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:04:39.819 32691 32691 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:04:39.819 32691 32691 E shadowsocks: bind: Address already in use
04-09 13:04:39.819 32691 32691 E shadowsocks: bind() error
04-09 13:11:43.283  1253  1253 D shadowsocks: initializing acl...
04-09 13:11:43.366  1253  1253 D shadowsocks: using tcp fast open
04-09 13:11:43.366  1253  1253 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:11:43.366  1253  1253 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:11:43.366  1253  1253 E shadowsocks: bind: Address already in use
04-09 13:11:43.366  1253  1253 E shadowsocks: bind() error
04-09 13:11:50.873  1328  1328 D shadowsocks: initializing acl...
04-09 13:11:50.967  1328  1328 D shadowsocks: using tcp fast open
04-09 13:11:50.967  1328  1328 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:11:50.967  1328  1328 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:11:50.967  1328  1328 E shadowsocks: bind: Address already in use
04-09 13:11:50.967  1328  1328 E shadowsocks: bind() error
04-09 13:12:00.112  1616  1616 D shadowsocks: initializing acl...
04-09 13:12:00.191  1616  1616 D shadowsocks: using tcp fast open
04-09 13:12:00.191  1616  1616 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:12:00.191  1616  1616 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:12:00.192  1616  1616 D shadowsocks: udprelay enabled
04-09 13:12:14.130  1616  1616 E shadowsocks: remote_recv_cb_recv: Connection reset by peer
04-09 13:12:17.169  1616  1616 E shadowsocks: getpeername: Transport endpoint is not connected
04-09 13:12:25.494  1945  1945 D shadowsocks: initializing acl...
04-09 13:12:25.530  1945  1945 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 13:12:25.530  1945  1945 D shadowsocks: using tcp fast open
04-09 13:12:25.530  1945  1945 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:12:25.530  1945  1945 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:12:25.530  1945  1945 D shadowsocks: udprelay enabled
04-09 13:12:52.276  2012  2012 D shadowsocks: initializing acl...
04-09 13:12:52.362  2012  2012 D shadowsocks: using tcp fast open
04-09 13:12:52.362  2012  2012 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:12:52.362  2012  2012 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:12:52.362  2012  2012 D shadowsocks: udprelay enabled
04-09 13:13:11.808  2012  2012 E shadowsocks: getpeername: Transport endpoint is not connected
04-09 13:13:16.288  2012  2012 E shadowsocks: remote_recv_cb_recv: Software caused connection abort
04-09 13:13:16.288  2012  2012 E shadowsocks: remote_recv_cb_recv: Software caused connection abort
04-09 13:13:31.079  2260  2260 D shadowsocks: initializing acl...
04-09 13:13:31.118  2260  2260 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 13:13:31.118  2260  2260 D shadowsocks: using tcp fast open
04-09 13:13:31.118  2260  2260 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:13:31.118  2260  2260 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:13:31.118  2260  2260 D shadowsocks: udprelay enabled
04-09 13:13:42.607  2399  2399 D shadowsocks: initializing acl...
04-09 13:13:42.678  2399  2399 D shadowsocks: using tcp fast open
04-09 13:13:42.678  2399  2399 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:13:42.678  2399  2399 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:13:42.679  2399  2399 D shadowsocks: udprelay enabled
04-09 13:14:54.388  2584  2584 D shadowsocks: initializing acl...
04-09 13:14:54.428  2584  2584 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-JHYr24lgkehJasCXPnlFow==/lib/arm/libobfs-local.so --fast-open -V" enabled
04-09 13:14:54.428  2584  2584 D shadowsocks: using tcp fast open
04-09 13:14:54.428  2584  2584 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:14:54.429  2584  2584 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:14:54.429  2584  2584 D shadowsocks: udprelay enabled
04-09 13:15:35.139  2729  2729 D shadowsocks: initializing acl...
04-09 13:15:35.220  2729  2729 D shadowsocks: using tcp fast open
04-09 13:15:35.220  2729  2729 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:15:35.220  2729  2729 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:15:35.220  2729  2729 D shadowsocks: udprelay enabled
04-09 13:29:59.512  4695  4695 D shadowsocks: initializing acl...
04-09 13:29:59.588  4695  4695 D shadowsocks: using tcp fast open
04-09 13:29:59.588  4695  4695 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:29:59.588  4695  4695 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:29:59.588  4695  4695 D shadowsocks: udprelay enabled
04-09 13:30:24.025  4868  4868 D shadowsocks: initializing acl...
04-09 13:30:24.096  4868  4868 D shadowsocks: using tcp fast open
04-09 13:30:24.096  4868  4868 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:30:24.096  4868  4868 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:30:24.097  4868  4868 D shadowsocks: udprelay enabled
04-09 13:30:25.584  4868  4868 E shadowsocks: invalid password or cipher
04-09 13:30:25.590  4868  4868 E shadowsocks: invalid password or cipher
04-09 13:30:26.135  4868  4868 E shadowsocks: invalid password or cipher
04-09 13:30:26.146  4868  4868 E shadowsocks: invalid password or cipher
04-09 13:30:26.334  4868  4868 E shadowsocks: invalid password or cipher
04-09 13:30:26.694  4868  4868 E shadowsocks: invalid password or cipher
04-09 13:30:26.709  4868  4868 E shadowsocks: invalid password or cipher
04-09 13:30:27.271  4868  4868 E shadowsocks: invalid password or cipher
04-09 13:30:27.818  4868  4868 E shadowsocks: invalid password or cipher
04-09 13:30:29.188  4913  4913 D shadowsocks: initializing acl...
04-09 13:30:29.267  4913  4913 D shadowsocks: using tcp fast open
04-09 13:30:29.267  4913  4913 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:30:29.267  4913  4913 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:30:29.267  4913  4913 D shadowsocks: udprelay enabled
04-09 13:30:49.481  5012  5012 D shadowsocks: initializing acl...
04-09 13:30:49.571  5012  5012 D shadowsocks: using tcp fast open
04-09 13:30:49.571  5012  5012 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:30:49.572  5012  5012 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:30:49.572  5012  5012 D shadowsocks: udprelay enabled
04-09 13:32:34.576  5371  5371 D shadowsocks: initializing acl...
04-09 13:32:34.660  5371  5371 D shadowsocks: using tcp fast open
04-09 13:32:34.660  5371  5371 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:32:34.660  5371  5371 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:32:34.660  5371  5371 D shadowsocks: udprelay enabled
04-09 13:32:37.632  5371  5371 E shadowsocks: invalid password or cipher
04-09 13:32:40.160  5371  5371 E shadowsocks: invalid password or cipher
04-09 13:32:41.850  5429  5429 D shadowsocks: initializing acl...
04-09 13:32:41.924  5429  5429 D shadowsocks: using tcp fast open
04-09 13:32:41.924  5429  5429 D shadowsocks: initializing ciphers... aes-128-gcm
04-09 13:32:41.924  5429  5429 D shadowsocks: listening at 127.0.0.1:1080
04-09 13:32:41.924  5429  5429 D shadowsocks: udprelay enabled
`

**Comment by triaqu** [comment] 2018-04-09 05:43
另外，4.5.5还有个bug，不知能不能在这里提交。就是在“分应用VPN“设置里，“应用设置到所有配置文件”无效。4.5.3正常

**Comment by madeye** [comment] 2018-04-09 05:52
@Mygod I don't see bind() errors in #1742.

**Comment by madeye** [comment] 2018-04-09 09:57
@triaqu Could you try this?

Disconnect the current server, switch the profile, then connect. Would you still see this issue again?

**Comment by triaqu** [comment] 2018-04-09 11:25
@madeye

 试了，
1。断开正常连接，切换到错误配置，连接报错，关闭连接。切换到正常配置，连接报错。

2，断开正常连接，切换到错误配置，连接报错，不关闭直接切换到正常配置，连接正常。

**Comment by madeye** [comment] 2018-04-10 08:02
@triaqu Could you try this APK? https://www.dropbox.com/s/9asq5gvypvrk1w9/mobile-universal-release.apk?dl=0

**Comment by triaqu** [comment] 2018-04-10 08:16
@madeye  正常了。无论是否断开再连还是直接切换，都没有问题。

**Comment by triaqu** [comment] 2018-04-10 08:25
4.5.5还有个BUG,在“分应用VPN“设置里，“应用设置到所有配置文件”无效。

**Comment by Mygod** [comment] 2018-04-10 18:54
@triaqu That seems to just be a cache inconsistency issue and it should be fixed via 1bc851d.

**Comment by Mygod** [comment] 2018-04-11 02:43
If that's the only change I think we can close this now.

**Comment by madeye** [comment] 2018-04-11 04:50
Sure. Let's close it now.

**Closed by madeye** 2018-04-11 04:50 UTC
Labels: bug
