### ISSUE TITLE
Shadowsocks Crashed

### ISSUE THREAD

**Issue by SpaceRoamer** [shadowsocks/shadowsocks-android#1546] opened 2018-01-03 10:07 UTC
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *7.0*
* Device: *Samsung S7*
* Shadowsocks version: 4.4.3
* Last version that did not exhibit the issue (if applicable): 4.3.3 and before

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: CHACHA20-IETF-POLY1305, AES-256-GCM
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
When I clicked the bottom right connect button, it didn't connect then crashed (A small window that says "Shadowsocks has stopped" popped up.

### What did you expect to see?
Connect fine, just like version 4.3.3 or before.

### What did you see instead?
A window popped out just said "Shadowsocks has stopped". This happened to the several servers I used without any success.

[catlog.txt](https://github.com/shadowsocks/shadowsocks-android/files/1599980/catlog.txt)

**Comment by madeye** [comment] 2018-01-03 10:51
Disable Xposed and try again.

**Comment by SpaceRoamer** [comment] 2018-01-04 01:23
I uninstalled Xposed but still no luck. BTW, I can't scroll to the bottom in the 'Profiles' tab but can do it on v4.4.2

**Comment by madeye** [comment] 2018-01-04 02:38
Please submit your catlog after disabling xposed.

**Comment by SpaceRoamer** [comment] 2018-01-04 03:21
[logcat_01-04-2018_11-12-16.txt](https://github.com/shadowsocks/shadowsocks-android/files/1602340/logcat_01-04-2018_11-12-16.txt)

**Comment by wongsyrone** [comment] 2018-01-04 03:59
It seems this is the root cause:

```
[01-04 11:12:12.370 27106:27106 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.github.shadowsocks:bg, PID: 27106
android.app.RemoteServiceException: Bad notification posted from package com.github.shadowsocks: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.github.shadowsocks user=UserHandle{0} id=1 tag=null key=0|com.github.shadowsocks|1|null|10399: Notification(pri=-2 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x62 color=0xff607d8b vis=PRIVATE semFlags=0x0 semPriority=0))
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```

Some refs:

https://stackoverflow.com/questions/18558066/couldnt-expand-remoteviews
https://github.com/OneSignal/OneSignal-Android-SDK/issues/263

**Comment by SpaceRoamer** [comment] 2018-01-04 04:03
I don't understand all these. Can you tell me what to do now?

**Comment by Mygod** [comment] 2018-01-04 04:14
Try reinstalling 4.4.3. There is no change to ServiceNotification between 4.3.3 and 4.4.3 afaic.

**Comment by Mygod** [comment] 2018-01-04 04:14
Try reinstalling 4.4.3. There is no change to ServiceNotification between 4.3.3 and 4.4.3 afaic.

**Comment by SpaceRoamer** [comment] 2018-01-04 04:17
Reinstall gives the same result :(

**Comment by Mygod** [comment] 2018-01-04 04:29
Could you try 4.4.0-4.4.2 as well?

**Comment by SpaceRoamer** [comment] 2018-01-04 05:37
All these pre-release versions from 4.4.0 to 4.4.3 I've already tried, same problem. Only versions that work are 4.3.3 and before.

**Comment by madeye** [comment] 2018-01-04 06:13
Have you tried reboot your device?

**Comment by SpaceRoamer** [comment] 2018-01-04 06:22
Definitely I've tried that. Uninstall 4.4.3, reinstall 4.4.3, reboot or not reboot in-between uninstall & install, ....

**Comment by madeye** [comment] 2018-01-04 06:33
I think it maybe related to our webp format icon. More specifically, it'd be caused by `ic_service_active`.

**Comment by SpaceRoamer** [comment] 2018-01-04 06:38
So I should expect to see the correction in the next build? Also, as said earlier, I cannot scroll to select servers in the 'Profile' tab in v4.4.3 but can do so in all other versions.

**Comment by madeye** [comment] 2018-01-04 06:48
Could you try this apk? https://www.dropbox.com/s/ztrot78c3ppw1ry/shadowsocks-nightly-4.4.4.apk

**Comment by SpaceRoamer** [comment] 2018-01-04 07:06
Still crashed! Uninstall, reinstall, reboot, all tried.
[logcat_01-04-2018_15-00-15.txt](https://github.com/shadowsocks/shadowsocks-android/files/1602648/logcat_01-04-2018_15-00-15.txt)

**Comment by madeye** [comment] 2018-01-04 08:26
Just tried on an Android 7.0 emulator. Everything works well.

It looks a third party bug that we cannot reproduce locally.

**Comment by SpaceRoamer** [comment] 2018-01-04 09:19
Looking at my logcat, do you see something a likely culprit?

**Comment by Mygod** [comment] 2018-01-04 11:05
According to crash statistics, there are a lot of users having this crash
and unfortunately we can't reproduce it. 😅

**Comment by madeye** [comment] 2018-01-04 13:25
Is possible that it's caused by some third party apps?

**Comment by madeye** [comment] 2018-01-04 13:47
Is there any special character in your profile name?

Have you changed your system fonts?

**Comment by SpaceRoamer** [comment] 2018-01-04 14:02
I switched back to system font, reboot but still no go. Profile names are all normal alphanumeric ones (a,b,c...1,2,3...-,_), no other special characters.

**Comment by SpaceRoamer** [comment] 2018-01-12 02:51
Finally found out the crash was caused by an app that tried to change the colors of the pulldown menu!! Strange that was never a problem for v4.3.3 and before and only happened in all those pre-release versions.  Perhaps you can take a look there. Thank you for the replies earlier!

**Comment by madeye** [comment] 2018-01-12 03:56
@SpaceRoamer Which app?

**Comment by SpaceRoamer** [comment] 2018-01-12 04:06
It's a custom rom control app (a system app called Supercontrol that comes with the rom - Superman ROM for Samsung S7) that can tweak SystemUI & other things of the rom, and the one that can modify the colors of the the pulldown menu of the notification panel is now identified as the culprit that causes the crash.

**Comment by Mygod** [comment] 2018-01-12 04:24
I think we can close this for now. If somebody else is experiencing this crash please open a new issue.

**Closed by Mygod** 2018-01-12 04:24 UTC
Labels: cannot reproduce, third-party bug
