### ISSUE TITLE
Media upload problem in Telegram since upgraded to shadowsocks-rust 1.9

### ISSUE THREAD

**Issue by arbabseyfola** [shadowsocks/shadowsocks-android#2681] opened 2021-02-23 21:29 UTC
Please read contributing guidelines. Thanks.

There is a problem in Telegram media uploading since shadowsocks rust was updated to version 1.9.
Same problem exist in telegram desktop with shadowsocks rust 1.9 client.

**Expected behavior**
Start upload media after sending.

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: Android 10 
 - Device: Mi 9T pro
 - Version: All versions after 5.1.7
 

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-poly1305 
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable): v2ray (websocket-tls)
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by madeye** [comment] 2021-02-23 22:48
@zonyitoo Can you take a look?

I can reproduce this locally.

**Comment by madeye** [comment] 2021-02-23 23:09
@arbabseyfola Can you confirm that the plugin is enabled in your profile?

I cannot reproduce this issue with any SIP003 plugin enabled.

**Comment by madeye** [comment] 2021-02-24 00:33
Interesting, it seems not able to be reproduced every time.

@arbabseyfola When this issue happening, can you kill telegram then try again? It's not clear how telegram implements its uploading mechanism, but it seems working from my side.

**Comment by arbabseyfola** [comment] 2021-02-24 01:23
> @arbabseyfola Can you confirm that the plugin is enabled in your profile?
> 
> I cannot reproduce this issue with any SIP003 plugin enabled.

Yes.
V2ray plugin is used.

**Comment by arbabseyfola** [comment] 2021-02-24 01:35
> Interesting, it seems not able to be reproduced every time.
> 
> @arbabseyfola When this issue happening, can you kill telegram then try again? It's not clear how telegram implements its uploading mechanism, but it seems working from my side.

This happens most of times for me. Force stop android app did not help. No such problem in 5.1.7 and before.

**Comment by zonyitoo** [comment] 2021-02-24 02:22
It is working on my Laptop with Telegram Desktop 2.5.9, macOS.

Running `sslocal` v1.9.0 in HTTP mode. I am trying with the SOCKS5 mode.

**Comment by dev4u** [comment] 2021-02-24 03:13
> It is working on my Laptop with Telegram Desktop 2.5.9, macOS.
> 
> Running `sslocal` v1.9.0 in HTTP mode. I am trying with the SOCKS5 mode.
> 
> EDIT: SOCKS5 mode is also working.
> 
> ![image](https://user-images.githubusercontent.com/1067951/108939324-7d065c80-768c-11eb-886e-62a05b6b3f57.png)
> 

PO主用的是手机版telegram，你好像没有安卓机，难为你了。

**Comment by zonyitoo** [comment] 2021-02-24 03:15
> Same problem exist in telegram desktop with shadowsocks rust 1.9 client.

Author confirmed that the Desktop version can also reproduce this issue.

**Comment by dev4u** [comment] 2021-02-24 03:20
我这边重现不了。
mi9 pro
telegram v7.5.0 2243

P.S.试试清除发送的缓存再试试。进入的方法:长按下方的版本。

![IMG_20210224_111814.jpg](https://user-images.githubusercontent.com/1210047/108942467-05d3c700-7692-11eb-9bb5-bd22b5024eb4.jpg)

**Comment by arbabseyfola** [comment] 2021-02-24 05:13
> > Same problem exist in telegram desktop with shadowsocks rust 1.9 client.
> 
> Author confirmed that the Desktop version can also reproduce this issue.

Now I Can't reproduce it on the desktop again! But android version has problem.

**Comment by madeye** [comment] 2021-02-24 05:21
@arbabseyfola can you try enabling airplane mode then disabling it, when you see the issue happens.

**Comment by arbabseyfola** [comment] 2021-02-24 05:42
> @arbabseyfola can you try enabling airplane mode then disabling it, when you see the issue happens.

It was not effective. But often a few times of stops and starts within the program solves the problem.

**Comment by madeye** [comment] 2021-02-24 05:51
It's still not clear to me why we see the stuck here. It should be related to how telegram do the uploading.

But one workaround is setting SOCKS5 proxy in telegram to 127.0.0.1:1080. It should solve your issue for now.

**Comment by arbabseyfola** [comment] 2021-02-24 06:06
> It's still not clear to me why we see the stuck here. It should be related to how telegram do the uploading.
> 
> But one workaround is setting SOCKS5 proxy in telegram to 127.0.0.1:1080. It should solve your issue for now.

Often I use proxy only mode with socks In telegram and same problem exist.

**Comment by zonyitoo** [comment] 2021-02-24 06:42
What exactly the problem was like? The program hangs or report errors?

**Comment by arbabseyfola** [comment] 2021-02-24 07:04
> What exactly was the problem like? The program hangs or reports errors?

**Comment by madeye** [comment] 2021-02-24 08:26
If setting SOCKS5 proxy didn't work for you, I guess you should be able to reproduce this on desktop as well.

@zonyitoo The uploading progress is freezing. From my local tests, switching airplane mode can force Telegram retry the uploading and get this issue temporally solved.

**Comment by zonyitoo** [comment] 2021-02-24 09:57
> > It is working on my Laptop with Telegram Desktop 2.5.9, macOS.
> > Running `sslocal` v1.9.0 in HTTP mode. I am trying with the SOCKS5 mode.
> > EDIT: SOCKS5 mode is also working.
> 
> PO主用的是手机版telegram，你好像没有安卓机，难为你了。

I managed to install an Android x86 simulator, and then `sslocal` reports: `ERROR accept failed with error: Function not implemented (os error 38)`... Da**

**Comment by dev4u** [comment] 2021-02-24 10:18
> I managed to install an Android x86 simulator, and then `sslocal` reports: `ERROR accept failed with error: Function not implemented (os error 38)`... Da**
> 
> Which means that this version of Android doesn't have `accept4`

这可能是个找问题的思路。
我的建议是，因为po主正常能用的版本，跟当前异常的版本相差有点大：ss升级了多进程模式、rust升级了tokio……所以能不能通过升级中间的版本来确认大概是什么时候的commit引入的问题。至少不用靠猜来确认。

**Comment by zonyitoo** [comment] 2021-02-24 10:42
Ok, I managed to run shadowsocks-android on an Android emulator.

![image](https://user-images.githubusercontent.com/1067951/108988781-d17efb80-76cf-11eb-8e09-6efaa3005cd2.png)

It is working well without plugins.

The .apk I downloaded from Releases doesn't ship with any plugins, so I cannot test with v2ray-plugin. How to install v2ray-plugin manually?

**Comment by madeye** [comment] 2021-02-24 10:44
You can download the APK here: https://github.com/shadowsocks/v2ray-plugin-android/releases/tag/v1.3.3

**Comment by zonyitoo** [comment] 2021-02-24 10:51
Working perfectly correctly with v2ray-plugin:

![image](https://user-images.githubusercontent.com/1067951/108990003-3b4bd500-76d1-11eb-9430-73a19af31b25.png)

**Comment by madeye** [comment] 2021-02-25 07:49
After updating to the latest telegram (Feb 25), I cannot reproduce this issue anymore...

**Comment by zonyitoo** [comment] 2021-02-25 07:53
Hmm, so Telegram is the one to be blame?

**Comment by arbabseyfola** [comment] 2021-02-25 11:22
The problem still exists!

![Screenshot_2021-02-25-14-45-29-995_org telegram messenger](https://user-images.githubusercontent.com/10263291/109145869-53c2fa80-7778-11eb-8464-4d941b43fa2c.jpg)
![IMG_20210225_144755](https://user-images.githubusercontent.com/10263291/109145976-781ed700-7778-11eb-80f2-9d91f5847726.jpg)
![Screenshot_2021-02-25-14-45-52-002_com github shadowsocks](https://user-images.githubusercontent.com/10263291/109146067-94bb0f00-7778-11eb-8b6e-c5ab90591896.jpg)
![Screenshot_2021-02-25-14-46-35-894_com miui securitycenter](https://user-images.githubusercontent.com/10263291/109146076-97b5ff80-7778-11eb-82d8-4033f8a30510.jpg)

Server side :
Shadowsocks-libev v3.3.5 + v2ray plugin v1.3.1

**Comment by dev4u** [comment] 2021-02-25 13:53
我遇过类似的问题，不过不是在telegram，而是在youtube app。
不用插件看看会不会缓解这种现象。

**Comment by arbabseyfola** [comment] 2021-02-25 17:38
> 我遇过类似的问题，不过不是在telegram，而是在youtube app。
> 不用插件看看会不会缓解这种现象。

In my country, the traffic of servers without plugins is detected and blocked very quickly.

**Comment by dev4u** [comment] 2021-02-26 03:00
方便展示一下你的插件在C/S上的运行参数吗？
如果可能，请试试如下操作：
调低tcp的超时时间，例如120s
服务端的mode设定为tcp_only。

**Comment by zonyitoo** [comment] 2021-02-26 03:41
I was testing it with Telegram for Android v7.0.5 (2245) x86_64.

Some hints for moving this issue forward:

1. Compatibility issue between `sslocal` and `ssserver`
    Try to replace `ssserver` from libev to the rust version and see if the problem still exists.
2. Server issue
    Your connection between servers are unstable, which leads to packet drops occationally. If v2ray-plugin failed to connect  the remote server, then `sslocal` normally won't report "connection failed" but blocks on `read()` for a very long time, because v2ray-plugin won't RST the connection actively.

Since I cannot reproduce this issue locally, I highly suspect it was the Server's issue.

**Comment by madeye** [comment] 2021-02-26 04:31
One possible issue is related to the long TCP connection. Maybe telegram tries to reuse some TCP connections, but they're already closed silently by shadowsocks due to timeout or something else.

@arbabseyfola Try shadowsocks-rust as your server, and make sure the server timeout is large enough, say > 3600 seconds.

**Comment by dev4u** [comment] 2021-02-26 08:48
> 2. Server issue
>     Your connection between servers are unstable, which leads to packet drops occationally. If v2ray-plugin failed to connect  the remote server, then `sslocal` normally won't report "connection failed" but blocks on `read()` for a very long time, because v2ray-plugin won't RST the connection actively.
> 
我认可这个猜测。建议在不清楚什么状况下，不要设置太大的超时时间。
另外有个现象可以观察一下，客户端发生等待、阻塞前，服务端是不是有发生数据重放？

**Comment by arbabseyfola** [comment] 2021-03-03 15:19
> One possible issue is related to the long TCP connection. Maybe telegram tries to reuse some TCP connections, but they're already closed silently by shadowsocks due to timeout or something else.
> 
> @arbabseyfola Try shadowsocks-rust as your server, and make sure the server timeout is large enough, say > 3600 seconds.

I apologize for the delay.  I tested with shadowsocks-rust V1.9.1 server and it seems that this problem no longer exists. The shadowsocks-rust client doesn't seem to be adhering to the protocol properly.

**Comment by zonyitoo** [comment] 2021-03-04 04:59
> The shadowsocks-rust client doesn't seem to be adhering to the shadowsocks protocol properly.

I doubt that. It seems to be a compatible issue.

**Comment by arbabseyfola** [comment] 2021-03-05 15:48
> > The shadowsocks-rust client doesn't seem to be adhering to the shadowsocks protocol properly.
> 
> I doubt that. It seems to be a compatible issue.
> 
> There should be no problem in the protocol level, or this problem must be presented in all of our previous tests.
> 
> I highly suspected that it is related to the timeout configurations.

How much timeout should I set?

**Comment by zonyitoo** [comment] 2021-03-05 15:56
Just delete it.

**Comment by arbabseyfola** [comment] 2021-03-05 17:44
> Just delete it.

Nothing changed!

**Comment by zonyitoo** [comment] 2021-03-05 18:26
Any idea? @madeye

**Comment by madeye** [comment] 2021-03-05 21:01
Yes, I think it's an issue related to timeout settings on the server.

**Comment by arbabseyfola** [comment] 2021-03-05 21:26
> Yes, I think it's an issue related to timeout settings on the server.

There is no problem with the same settings and ss-rust server.

**Comment by madeye** [comment] 2021-03-05 21:33
Set the timeout to 3600 for shadowsocks-libev server and try again.

The timeout logic would be sightly different between implementations.

**Comment by arbabseyfola** [comment] 2021-03-06 07:01
> Set the timeout to 3600 for shadowsocks-libev server and try again.
> 
> The timeout logic would be sightly different between implementations.

Nothing changed. The problem still exists

**Comment by madeye** [comment] 2021-03-06 07:08
Post your server's config file here.

**Comment by arbabseyfola** [comment] 2021-03-06 08:11
> Post your server's config file here.

#My Config
ENV SERVER_ADDR 0.0.0.0
ENV SERVER_PORT 443
ENV TIMEOUT 3600
ENV METHOD chacha20-ietf-poly1305
ENV PASSWORD xxxxxxx
ENV ARGS --plugin v2ray-plugin --plugin-opts server;host=********** -u


CMD exec ss-server \
    -s $SERVER_ADDR \
    -p $SERVER_PORT \
    -k $PASSWORD \
    -m $METHOD \
    -t $TIMEOUT \
    -d $DNS_ADDRS \
    --reuse-port \
    --no-delay \
    $ARGS

**Comment by madeye** [comment] 2021-03-06 08:14
Try remove the following items

--reuse-port
--no-delay

If it still doesn't work, please use shadowsocks-rust for now.

**Comment by arbabseyfola** [comment] 2021-03-06 08:20
> Try remove the following items
> 
> --reuse-port
> --no-delay
> 
> If it still doesn't work, please use shadowsocks-rust for now.

Not working :(

**Comment by Mygod** [comment] 2021-04-16 00:05
So... what's the state on this issue?

**Comment by zonyitoo** [comment] 2021-04-16 00:43
Couldn't be reproduce and don't know why.

**Comment by Mygod** [comment] 2021-05-06 05:25
Closing due to inactivity.

**Comment by FinecoFinit** [comment] 2021-05-26 05:45
Hey, the problem is still exist. Pls, reopen

**Comment by zonyitoo** [comment] 2021-05-27 13:56
Could you reproduce?

**Comment by thegreathir** [comment] 2021-08-17 18:33
Still problem here...
I setup shadowsocks-libev (v3.3.5) and v2ray-plugin (v1.3.1) on server and shadowsocks android (v5.2.5) and v2ray(v1.3.2) on my android phone. Both client apps are installed from google play. I can not send any media in telegram application.

After switching server side program to shadowsocks-rust (v1.11.2) everything fixed and I can upload anything without problem.
I just want to notify you that problem is still there and if you think it is a shadowsocks-libev problem tell me to issue it on their repo. But I think the problem is related to android client because with my libev sever, Shadowrocket (iOS client) worked fine.

NOTE: I played with "timeout" in configuration and nothing changed. (I set to 60, 100, 200, 3600, 7200, not set)

**Comment by zonyitoo** [comment] 2021-08-18 07:32
When your telegram couldn't send any media files, could you visit websites or using other Apps?

**Comment by thegreathir** [comment] 2021-08-18 10:54
Yes, I can visit other websites and I can also upload files in Gmail app.
I use ss-local in my laptop since one year ago and everything is OK with both rust and libev server. (Telegram desktop client works well)
Which packet do you mean? You want me to run something like tshark in server and send you the results?

**Comment by zonyitoo** [comment] 2021-08-18 11:03
1. Try to run `sslocal` from shadowsocks-rust on your laptop and see if the problem could be reproduced.
2. Capture packets with like `tcpdump` on your server and see if it actually receives requests from your phone (shadowsocks-android App).

**Comment by thegreathir** [comment] 2021-08-18 11:18
I want to check if I understand it correctly:
ss android <------> sslocal (rust) <--------> ss-server (libev)
The connection should setup like that?

**Comment by zonyitoo** [comment] 2021-08-18 11:18
The ss-android already have a `sslocal`.

**Comment by zonyitoo** [comment] 2021-08-18 11:22
* 1st setup

```
sslocal (rust) with v2ray-plugin -> ss-server (libev) with v2ray plugin
```

on Your laptop to test if there is anything wrong in the protocol level.

* 2nd setup

```
ss-android (with sslocal (rust)) with v2ray-plugin -> ss-server (libev) with v2ray-plugin
```

try to capture packets on the server and see if it actually receives the packet from the client (ss-android)

* 3rd setup

Like the 2nd setup, but without the `v2ray-plugin` for testing if it is Ok without plugin.

**Comment by thegreathir** [comment] 2021-08-18 11:29
I setup 2nd setup and exactly when I start uploading media in android app I see following error on the server:

```
2021-08-18 11:27:21 ERROR: failed to handshake with 127.0.0.1: malicious fragmentation
```

I can not test 3rd setup :(, pure Shadowsocks is blocked here.

**Comment by zonyitoo** [comment] 2021-08-18 11:44
It was reported from here: https://github.com/shadowsocks/shadowsocks-libev/blob/abcf85e98300762e4f31953cecf635ab182ef859/src/server.c#L984-L989

Interesting. What's this `frag`?

It that happened always when the problem reproduced?

**Comment by zonyitoo** [comment] 2021-08-18 11:51
Is that for detecting if the first AEAD packet was too large? @madeye

**Comment by thegreathir** [comment] 2021-08-18 11:52
I tested 1st setup and everything works fine with sslocal (rust). telegram can upload media easily.
Yes it happens every time I start uploading...
Is there anything else I should provide you? I it necessary to report `tcpdump` result?

**Comment by zonyitoo** [comment] 2021-08-18 11:53
Maybe not. If that happens repeatly, then it may be the root cause. Please consider reopen this issue @Mygod

**Comment by zonyitoo** [comment] 2021-08-18 11:57
First of all, @thegreathir Please try to comment [these lines](https://github.com/shadowsocks/shadowsocks-libev/blob/abcf85e98300762e4f31953cecf635ab182ef859/src/server.c#L984-L991) and compile a new `ss-server` and run it on your server if it fixes your issue.

**Comment by madeye** [comment] 2021-08-18 12:00
In libev implementation, I assume the first AEAD chunk should not be split into multiple packets.

The assumption is for avoiding active probe.

**Comment by madeye** [comment] 2021-08-18 12:02
I think we can refine this in libev implementation. Any PR is welcome.

**Comment by thegreathir** [comment] 2021-08-18 12:04
@zonyitoo commenting those lines fixed the issue...

**Comment by zonyitoo** [comment] 2021-08-18 12:12
Ok. Well, this is the root cause. Now we finally know what causes the issue.

Two solutions:

1. shadowsocks-libev removes this check.
2. shadowsocks-rust limits the first AEAD packet in one mtu.

**Comment by madeye** [comment] 2021-08-18 12:34
Nope, I just make sure the socket buffer size is large enough, no other special handling.

**Comment by zonyitoo** [comment] 2021-08-18 12:36
So there is a chance that `ss-server` would reject the packet sent from `ss-local` if it is too large (AEAD's packet size too large).

**Comment by Mygod** [comment] 2021-08-18 23:16
Reopening as requested.

Why doe shadowsocks-rust do this fragmentation?

**Comment by madeye** [comment] 2021-08-19 00:39
Try this commit: https://github.com/shadowsocks/shadowsocks-libev/commit/b9117559000e1bdee4a84383c537ca5b4b7fe8dc

**Comment by zonyitoo** [comment] 2021-08-19 03:38
> Why doe shadowsocks-rust do this fragmentation?

Well, actually shadowsocks-rust doesn't do fragmentation.

The code that @madeye have just removed are trying to `decrypt` the first handshake packet in **two** `read()`s. Because AEAD packets have a `length` field, so the `decrypt` call will continously return `CRYPTO_NEED_MORE` if it didn't receive `length` bytes of packet payloads.

I suspect that on Android, when cooperating with the Telegram.app, the `sslocal`'s `read()` may get a very big buffer. The packaged AEAD packet won't be able to get in 2 `read()`s.

I still couldn't reproduce it on my Laptop. It should be a special corner case on Android when cooperate with `tun2socks`.

**Comment by Mygod** [comment] 2021-08-22 06:28
So I guess we can close this now? Could shadowsocks-rust somehow get around this issue regardless?

**Comment by zonyitoo** [comment] 2021-08-22 06:30
Maybe. But it would be ugly. AEAD packets have size limit 0x3FFF. If we force limit the first packet to MTU, then it should also become an obvious pattern.

I would suggest closing this.

**Comment by Mygod** [comment] 2021-08-22 07:12
I don't think the solution is to force the first packet to MTU. You only need to make sure that the header fits within the first packet?

**Comment by zonyitoo** [comment] 2021-08-22 07:49
https://github.com/shadowsocks/shadowsocks-libev/commit/b9117559000e1bdee4a84383c537ca5b4b7fe8dc requires `crypto->decrypt(buf, server->d_ctx, SOCKET_BUF_SIZE)` successfully decrypt the first handshake packet in 2 `read()` calls (`#define MAX_FRAG 1`). Since every AEAD packets' have a length field, so if the first packet is very large (larger than 2 MTU), then you wouldn't be able to get the full AEAD packet within 2 `read()`s.

**Comment by Mygod** [comment] 2021-08-22 08:12
I was talking about the socks header. So I guess in shadowsocks-rust you send the data along with the header in one payload then.

**Closed by Mygod** 2021-08-22 08:12 UTC
Labels: cannot reproduce, third-party bug

**Comment by 0xj0hn** [comment] 2022-04-12 20:11
i had same problem, but when i use another encryption mode instead of chacha-,.... it has been working perfectly and can upload anything on Telegram...
i use **aes-256-cfb** as my encryption method
maybe my solution would fix your problem.

**Comment by zonyitoo** [comment] 2022-04-13 06:46
The root cause of this issue have already been identified. There already is a solution.
