### ISSUE TITLE
import from clipboard failed

### ISSUE THREAD

**Issue by chrimiway** [shadowsocks/shadowsocks-android#1178] opened 2017-03-22 07:26 UTC
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 7.0
* Shadowsocks version: v4.1.3

### What did you do?
import address from clipboard
(the syntax is correct)

### What did you expect to see?
successfully imported. Q_Q

### What did you see instead?
import failed. Q_Q

**Comment by chrimiway** [comment] 2017-03-22 07:50
It was copied from QR code and it worked on older version (3.4.2).

**Comment by Mygod** [comment] 2017-03-22 07:52
If it's base64-encoded, could you post the decoded URL with sensitive information masked?

**Comment by chrimiway** [comment] 2017-03-22 07:58
ss://YWVzLTI1Ni1jZmI6NDAxMjU2MDBAMTg4LjE2Ni4xODYuMTI5OjQ0Mwo=

I don't know what to mask...This address is posted on the internet, I won't get into trouble right?

**Comment by Mygod** [comment] 2017-03-22 08:03
Duplicate of #1153. Import it with the old version and upgrade for now.

**Closed by Mygod** 2017-03-22 08:03 UTC
