### ISSUE TITLE
New android app changes local dns lookup behavior

### ISSUE THREAD

**Issue by chadlangston** [shadowsocks/shadowsocks-android#2664] opened 2021-01-22 01:08 UTC
Love the app. The latest update changed the way dns lookups are handled. I am using the Bypass LAN feature and it used to use my local dns for all dns lookups. This is a requirement for me. Since the new update, all my dns lookups are being sent to the Remote DNS that is configured in the profile. Please add a way for me to continue using my local dns for all lookups when the Bypass LAN feature is enabled.

Thanks!

**Comment by madeye** [comment] 2021-01-22 11:46
I cannot reproduce your problem locally.

Double check if you enabled `Private DNS` in your system settings.

**Comment by chadlangston** [comment] 2021-01-22 13:36
Private DNS was set to automatic. I just set it to off. But, after connecting to Shadowsocks a DNS leak test still shows the remote DNS in use. ![Screenshot_20210122-083355.png](https://user-images.githubusercontent.com/34315075/105497343-b19d8780-5c8c-11eb-9848-269d602f465b.png)

Also, using an alternate open VPN client that allows me to specifically set the DNS, the above DNS leak test reports the correct DNS.

**Comment by chadlangston** [comment] 2021-01-22 13:41
Also, I'm running Shadowsocks 5.2.1 on the latest version of Android 11.

**Comment by madeye** [comment] 2021-01-24 00:27
From your screenshot, `bypass LAN` works as expected. We expect any public domain name should be resolved by the remote DNS.

BTW, `bypass LAN` cannot avoid DNS leaks, as any local hostname would be resolved by the local resolver.

**Comment by Mygod** [comment] 2021-01-24 00:43
@madeye Shouldn't bypass LAN try both resolvers?

**Comment by madeye** [comment] 2021-01-24 00:53
@Mygod Right, I mean only local hostname's result would be token from local resolver.

**Comment by Mygod** [comment] 2021-01-24 00:56
I don't think dnsleaktest tests local hostnames?

**Comment by madeye** [comment] 2021-01-24 01:01
Yes, I don't think dnsleaktest is related to the issue described here.

**Comment by chadlangston** [comment] 2021-01-24 15:16
The dns leak test is just what I was using to see which DNS server was being used. My local dns is Pihole followed by a cloudflared dns proxy for all the fowarded dns queries. So, when my local dns is being used the dns leak test shows Cloudflare dns not Google.

Anyway, it was working for me before the last Android update. If the Bypass Lan feature is designed to use my local dns first, then the Remote DNS for names that do not resolve locally, that's helpful to know, but it doesn't work for me.

My particular needs are hard to achieve since even systems like Nord VPN that allow me to specify my local dns will fail over to the VPN dns if the local dns doesn't resolve the name, as is the case with many Pihole queries. (The Nord VPN Android client works for me, but their Mac client exhibits the behavior above.)

Thanks for letting me know! I'd love to see a local dns feature in Shadowsocks some day that would fit my set up, but I totally understand if it doesn't make it into the plans :)

Best!

**Comment by madeye** [comment] 2021-01-29 08:14
@chadlangston By local DNS, do you mean the DNS server setup in your LAN environment or a DNS server setup on your remote server?

**Comment by chadlangston** [comment] 2021-01-29 12:46
A DNS server in my LAN environment.

**Comment by Mygod** [comment] 2021-01-29 22:28
It seems that DNS relay is indeed not working 100% properly. In my extended test of dnsleaktest, only 1 out of 6 round found two servers, which should be the expected behavior.

**Comment by Mygod** [comment] 2021-04-16 00:07
Ok great I can no longer reproduce this on latest master.

**Closed by Mygod** 2021-04-16 00:07 UTC
Labels: bug
