### ISSUE TITLE
Bypass LAN doesn't work.

### ISSUE THREAD

**Issue by axxop** [shadowsocks/shadowsocks-android#2361] opened 2019-11-22 09:36 UTC
**Describe the bug**
Bypass LAN doesn't work.

**To Reproduce**
Select an available server, profile use "Bypass LAN and mainland China", open your router web manager page under WIFI.

**Expected behavior**
I can open this page.

**Screenshots**
None

**Smartphone (please complete the following information):**
Android 10 Pixel 3
Andoird 10 Emulator
Shadowsocks is latest beta version

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
None

**Comment by axxop** [comment] 2019-11-28 07:52
I tried the latest pixel 3 firmware and the latest shadowsocks (from play store), still not working.

**Comment by axxop** [comment] 2019-11-28 07:52
If other information is needed, I can add it.

**Comment by iKirby** [comment] 2019-11-28 09:17
Same on my Pixel 3a, but it works on Pixel 1 with the same configuration.

**Comment by madeye** [comment] 2019-11-28 09:54
Reproduced on Android 10.

It looks a bug of Android 10, which breaks the assumption that not routing traffic should fall through the underlying network interfere.

**Comment by madeye** [comment] 2019-11-28 10:47
Try this APK: https://drive.google.com/open?id=1jYyg8zhu2Ou9sYR76vVvjNQ7bm62aWj1

**Comment by axxop** [comment] 2019-11-28 11:28
> Try this APK: https://drive.google.com/open?id=1jYyg8zhu2Ou9sYR76vVvjNQ7bm62aWj1

It works fine. Thanks for your work.

**Comment by iKirby** [comment] 2019-11-28 12:24
> Try this APK: https://drive.google.com/open?id=1jYyg8zhu2Ou9sYR76vVvjNQ7bm62aWj1

I can also confirm that this works. Thanks!

**Comment by Mygod** [comment] 2019-12-09 03:36
I don't understand. I cannot reproduce this on my device or emulator (after reverting e9e5c1c062743016808d97ea00e819deb2742b0d).

@madeye Could you share more details on this? What routing rule was changed in Android 10?

**Comment by iKirby** [comment] 2019-12-09 04:02
It seems that e9e5c1c doesn't actually fix this. I found that I still can't access FX Web Access (manage files on phone from the web) from other devices in the same LAN. (I can access router admin page though.)

This issue is probably introduced by something in November Android update.

On Pixel 1, even with the final update, security patch level is still `2019-10-06`. I have Shadowsocks 4.8.5 (which doesn't contain the fix) installed on the device, and bypass LAN & China works well. I can use FX Web Access without shutting down VPN service or adding FX to bypass list.

On Pixel 3a, I updated to `2019-11-05` security patch just the second day I got the device, I didn't use FX Web Access when it was on October patch. So I'm not sure it is caused by November update, just a guess.

**Comment by axxop** [comment] 2019-12-09 07:37
Same as @iKirby , [kdeconnect-android](https://github.com/KDE/kdeconnect-android) doesn't work too.
Can't scan other devices under the same WIFI network. Works fine on older android versions (android 9)

**Comment by Mygod** [comment] 2019-12-09 11:42
Reopen this for now for future investigation.

@madeye Can you reproduce this now?

**Comment by madeye** [comment] 2019-12-09 13:47
Interesting, I cannot reproduce this issue now.

**Comment by axxop** [comment] 2019-12-09 15:41
![image](https://user-images.githubusercontent.com/53638052/70449492-0b6cdd80-1add-11ea-825b-aa1668531614.png)

Reproduced on Andoird 10 Emulator
Reproduced on OnePlus6T Android10 BuildVersion: OP6T_H2_BETA_32
Shadowsocks 4.8.5

**Comment by Mygod** [comment] 2019-12-13 15:48
Just checked again and failed to reproduce this with both versions.

Emulator version: 29.3.0
Emulator build number: `sdk_gphone_x86_64-userdebug 10 QSR1.191030.002 5978551 dev-keys
QSR1.191030.002 5978551 dev-keys`

@madeye I suggest we revert e9e5c1c. No matter where the packet is routed, it should always be bypassed correctly so whatever is wrong with this, it should not relate to this repo.

**Comment by madeye** [comment] 2019-12-13 23:09
Sure, let's revert e9e5c1c first.

I think there's some special precondition preventing me reproducing this issue again.

I agree it looks not related to our implementation.

**Comment by Mygod** [comment] 2019-12-18 15:28
@madeye 
> #2361
> 
> @Mygod It looks Google broke something in their recent security patches.

Do you have a device that has the latest security patches?

**Comment by Mygod** [comment] 2019-12-18 15:45
Tested on Android 9 2019-12 security patches and were not able to reproduce.

**Comment by madeye** [comment] 2019-12-22 00:07
I cannot reproduce either on EMUI 10 with 2019-12 security patch.

**Comment by hybtoy** [comment] 2020-01-26 21:52
@madeye @Mygod 
Gents, 
I have a bit different problem. If the route is Bypass Lan - I can't access reddit.com (connection refused). If route is ALL - I can access reddit.com. Very strange.

**Comment by LGA1150** [comment] 2020-02-05 03:49
Same issue. Can't open router webpage in bypass LAN/GFWList mode.

App Version: 5.0.3
Device: OnePlus 7T
OS: Oxygen OS 10.0.7 (Android Q)
Security Patch: 2019-11-01

**Comment by BROBIRD** [comment] 2020-02-15 07:38
Same issue in bypass LAN and Mainland China mode.
App Version: 5.0.4
Device: Huawei Honor V20
OS: EMUI 10.0.0.189 (Android Q)
Security Patch: 2019-12-01

Additional:
If `IPv6 Route` option is `OFF`, then it seems works fine.

**Comment by iKirby** [comment] 2020-02-15 13:53
Tried turning off IPv6 Route, and I can confirm that it works on Pixel 3a (QQ1A.200205.002).

**Comment by madeye** [comment] 2020-02-15 14:04
Interesting, it looks to new IPv6 routing rules.

@Mygod Any thoughts?

**Comment by Mygod** [comment] 2020-02-16 02:12
Let me take a look later.

**Comment by Mygod** [comment] 2020-02-16 05:42
@madeye Could you try maybe `addRoute` 2000::/3 instead of ::/0?

**Comment by Mygod** [comment] 2020-02-18 16:26
Fixed via #2440.

**Closed by Mygod** 2020-02-18 16:26 UTC
Labels: third-party bug

**Comment by Mygod** [comment] 2020-12-11 02:05
@madeye Can you reproduce this bug now after reverting the patch? I cannot seem to do it...

P.S. There are also some updates over at the issue at Google: https://issuetracker.google.com/issues/149636790

**Comment by madeye** [comment] 2020-12-11 02:11
I don't have any Android 10 device now. Maybe it's already fixed?

**Comment by Mygod** [comment] 2020-12-11 05:51
I couldn't reproduce it on my Android 10 either. Would you be free to test it on the emulator perhaps? 😛

**Comment by madeye** [comment] 2020-12-11 05:53
I suggest keep this workaround for now, given it works well...

**Comment by Mygod** [comment] 2020-12-11 06:00
Sure but the fix suggested by the Google folk might be worth looking into.

**Comment by madeye** [comment] 2020-12-11 07:58
I revert the change and tried on the Android 10 emulator:

1. With IPv6 routing enabled, any IPv4 LAN address cannot be reached.
2. Adding `allowFamily()` to the VPN builder doesn't help. The IPv4 LAN still cannot be reached.

**Comment by Mygod** [comment] 2020-12-11 15:39
Hmm all of a sudden I can reproduce this on my Android 10 device again. It does seem to be fixed in Android 11?

**Comment by PRIHLOP** [comment] 2021-06-05 11:58
On Android 10 with ipv6 turned on in Wi-Fi network this issue is still happen.
Maybe it happens with ipv6 addressing in LAN?
In my case issue happens with v2ray plugin or without it(in tcp/udp mode).
