### ISSUE TITLE
升级到5.2.3或5.2.4后，juicessh、vlc/kodi访问nfs不正常

### ISSUE THREAD

**Issue by shixudong2020** [shadowsocks/shadowsocks-android#2751] opened 2021-06-28 01:51 UTC
shadowsocks升级到5.2.3或5.2.4后，JuiceSSH通过SS访问远端ssh服务器，第一次总是提醒“connection error（1005）：Socket error：Connection retset by peer 你想重试吗？”，一般重试一次后即正常，偶尔需要重试多次。而vlc/kodi通过SS则干脆无法访问nfs服务器。在使用5.2.2时，无上述异常现象，升级到5.2.3或5.2.4后，出现上述异常，卸载并重新安装5.2.2后，能恢复正常。why？

**Comment by vevsvevs** [comment] 2021-06-28 23:53
Same here.

**Comment by shixudong2020** [comment] 2021-06-29 15:35
经反复测试，终于找到bug所在了。ss服务器使用域名就会出现上述问题，改为ip后就一切正常。我是在家里搭了一个SS服务器，家里的公网IP经常会变，所以搞了一个ddns。估计是5.2.3修改ddns相关程序时改出问题来了。

**Comment by Mygod** [comment] 2021-06-29 15:59
Fill out the bug template.

**Comment by shixudong2020** [comment] 2021-06-30 01:15
**Describe the bug**
ss服务器使用域名，ss升级到5.2.3或5.2.4后，JuiceSSH通过ss访问远端ssh服务器，第一次总是提醒“connection error（1005）：Socket error：Connection retset by peer 你想重试吗？”，一般重试一次后即正常，偶尔需要重试多次。而vlc/kodi通过ss则干脆无法访问nfs服务器。在使用5.2.2时，无上述异常现象，升级到5.2.3或5.2.4后，出现上述异常，卸载并重新安装5.2.2后，能恢复正常。如ss服务器改用ip地址，使用5.2.3或5.2.4也正常。

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
![微信图片_20210630091058](https://user-images.githubusercontent.com/64650495/123886951-2636c980-d983-11eb-9e97-59960dd96de8.jpg)

![微信图片_20210630091244](https://user-images.githubusercontent.com/64650495/123887082-69913800-d983-11eb-82d3-9d3243b7644e.jpg)

![微信图片_20210630091249](https://user-images.githubusercontent.com/64650495/123887095-7746bd80-d983-11eb-807b-7e1c63d0b7cf.jpg)


**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred]
 - Device: [e.g. Google Pixel XL]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:chacha20-ietf-poly1305
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [x ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
Add any other context about the problem here.

**Comment by Mygod** [comment] 2021-06-30 01:30
Fill out the *full* form.

**Comment by Mygod** [comment] 2021-06-30 01:46
Furthermore, are you using Android private DNS? What DNS do you have configured?

**Comment by madeye** [comment] 2021-06-30 01:50
@zonyitoo What's the default timeout of shadowsocks-rust's internal DNS resolver?

This issue looks related to the DDNS provider's resolving performance, causing DNS timeout.

**Comment by Mygod** [comment] 2021-06-30 01:51
@madeye From my testing, the local DNS result seems cached by the system but it might not be the case on some ROM.

**Comment by shixudong2020** [comment] 2021-06-30 02:17
> Furthermore, are you using Android private DNS? What DNS do you have configured?

手机没有root，无论使用4G还是wifi，全是自动获取dns，5.2.2(含)以前ss服务器使用域名访问一直正常

**Comment by zonyitoo** [comment] 2021-06-30 02:20
https://github.com/shadowsocks/shadowsocks-rust/blob/19bc88bcb92ce6f227add410c92d5b40abe5e969/crates/shadowsocks-service/src/local/dns/server.rs#L459

5 seconds.

**Comment by shixudong2020** [comment] 2021-07-01 07:08
还是有一点没有想明白，5.2.2(含)以前版本通过域名访问ss服务器就一切正常，但ss客户端启动时，因为ss客户端还没有连通ss服务端，此时，对ss服务器域名的解析应该也是本地解析吧，为何5.2.2(含)以前版本就正常，5.2.3/5.2.4就出现异常呀？还有5.2.3/5.2.4下，JuiceSSH通过SS访问远端ssh 域名服务器，一般选择重试后就正常，而退出JuiceSSH后重新访问，又重复出现上述现象，至于浏览器通过ss访问，目前没有感觉异常。

**Comment by Mygod** [comment] 2021-07-04 04:19
fill out the full template or else

**Comment by Mygod** [comment] 2021-07-05 23:54
Ok I can reproduce this now. Let me look into it.

**Comment by madeye** [comment] 2021-07-06 00:20
Guess it's related to the DNS timeout in shadowsocks-rust.

**Comment by Mygod** [comment] 2021-07-06 00:22
I am seeing a lot of `ERROR udp relay 127.0.0.1:44537 -> 74.125.195.95:443 (proxied) with 1350 bytes, error: dns resolve <ss host:port> error: resolve empty`.

**Comment by Mygod** [comment] 2021-07-06 00:23
Also `io error: Broken pipe (os error 32)`. Maybe too many open files?

**Comment by madeye** [comment] 2021-07-06 00:26
Can we force using local resolver for the`ss-host`? 

> Also io error: Broken pipe (os error 32). Maybe too many open files?

It's possible if we keep getting UDP requests.

**Comment by Mygod** [comment] 2021-07-06 00:27
I think that is the current behavior.

**Comment by Mygod** [comment] 2021-07-06 00:50
`local_dns_path` seems to always return the correct result despite `libsslocal` complaining. @zonyitoo Any idea?

Another thing I noticed is that every time a connection is made, `AAAA` is queried twice to `local_dns_path`. Why is this?

**Comment by Mygod** [comment] 2021-07-06 00:55
@madeye @zonyitoo I will leave this one to you guys as the Android part seems to be responding correctly. 😛

**Comment by madeye** [comment] 2021-07-06 00:57
Hmm, but I cannot reproduce the issue locally. Can you enlarge the 5 sec timeout and try again?

**Comment by Mygod** [comment] 2021-07-06 00:57
It seems you need a large number of concurrent sessions to trigger the issue. `local_dns_path` responds instantly since the results are cached by the system, so no timeout issue here.

**Comment by madeye** [comment] 2021-07-06 01:02
If so, we may remove the cache from unix_stream lookup here: https://github.com/shadowsocks/shadowsocks-rust/blob/0b1630d1c6abcec3861b1eec39b266e1dad206e5/crates/shadowsocks-service/src/local/dns/client_cache.rs#L129

**Comment by Mygod** [comment] 2021-07-06 01:04
Yes. In fact I don't think the cache is working since `local_dns_path` is receiving 3 queries every time a new connection is made. Also caching in ss-rust is a terrible idea: https://github.com/shadowsocks/shadowsocks-rust/pull/345#issuecomment-874380944

**Comment by madeye** [comment] 2021-07-06 01:14
It looks shadowsocks-rust only cached the socket, not the results. I think @zonyitoo just wants to reuse the socket to the local resolver.

**Comment by Mygod** [comment] 2021-07-06 01:18
I am pretty sure my implementation does not permit connection reuse. 🤔

**Comment by madeye** [comment] 2021-07-06 01:18
Okay, I think we found the issue here.

**Comment by Mygod** [comment] 2021-07-06 01:20
🤔 I don't think you can ever assume connection reuse to work for DNS, maybe except for UDP.

**Comment by Mygod** [comment] 2021-07-06 01:21
Also `local_dns_path` does receive 3 valid queries for every connection, so I do not think what you said is the issue.

**Comment by shixudong2020** [comment] 2021-07-06 01:24
我估计与5.23的Refined DDNS support有关，但最让我不解的是，如前一贴所述：5.2.2(含)以前版本通过域名访问ss服务器一切正常，但ss客户端启动时，因为ss客户端还没有连通ss服务端，此时，对ss服务器域名的解析也需要本地解析，为何5.2.2(含)以前版本就正常，5.2.3/5.2.4就出现异常呀！

**Comment by madeye** [comment] 2021-07-06 01:30
Please try again with this APK: https://drive.google.com/file/d/1OMgPLhiLoU0_b9lTYWfOvp6SMqO7kk8_/view?usp=sharing

It disables the connection reuse for unix stream lookup.

@Mygod @shixudong2020

**Comment by shixudong2020** [comment] 2021-07-06 01:37
这个版本正常了，难道5.2.2处理SS服务器域名时没有使用connection reuse for unix stream lookup？

**Comment by madeye** [comment] 2021-07-06 01:40
> 这个版本正常了，难道5.2.2处理SS服务器域名时没有使用connection reuse for unix stream lookup？

Right, we don't have this before 5.2.3.

**Comment by Mygod** [comment] 2021-07-06 01:42
@madeye Push the changes to a PR and I will test?

**Comment by madeye** [comment] 2021-07-06 01:45
See https://github.com/shadowsocks/shadowsocks-rust/pull/567

**Comment by Mygod** [comment] 2021-07-06 03:36
Fixed via https://github.com/shadowsocks/shadowsocks-android/commit/247c4a1f36d44e1d8d15f5d715264b959b3a6b0c I suppose.

**Closed by Mygod** 2021-07-06 03:36 UTC
Labels: bug

**Comment by imReker** [comment] 2021-08-31 13:04
My Firebase Crashlytics reported lots of similar problems in `LocalSocketListener`, including `Broken pipe`, `Too many opened files` and `Bad file descriptor`, all lead to handle leak, the biggest suspect is UNIX stream/DNS related code.


[org.shadowsocks.xx_issue_19bc73ad993aad4d5fe278892d584231_error_session_61279182004D00013C85A04AC568A81B_DNE_5_v2.log](https://github.com/shadowsocks/shadowsocks-android/files/7084076/org.shadowsocks.xx_issue_19bc73ad993aad4d5fe278892d584231_error_session_61279182004D00013C85A04AC568A81B_DNE_5_v2.log)
[org.shadowsocks.xx_issue_274bc2d242720049275714683d3d4cc5_error_session_6127B31401C900010D2CF9C39D05D8E2_DNE_0_v2.log](https://github.com/shadowsocks/shadowsocks-android/files/7084077/org.shadowsocks.xx_issue_274bc2d242720049275714683d3d4cc5_error_session_6127B31401C900010D2CF9C39D05D8E2_DNE_0_v2.log)
[org.shadowsocks.xx_issue_2d5e1ddcbf72ff6f25953b540bd48ff5_error_session_6127C4D9026F00011AC0A04AC568A81B_DNE_0_v2.log](https://github.com/shadowsocks/shadowsocks-android/files/7084080/org.shadowsocks.xx_issue_2d5e1ddcbf72ff6f25953b540bd48ff5_error_session_6127C4D9026F00011AC0A04AC568A81B_DNE_0_v2.log)
